import express from 'express';
import { createServer } from 'http';
import { Server } from 'socket.io';
import cors from 'cors';
import crypto from 'crypto';
import path from 'path';

type Mode='answer'|'bluff'|'trap'|'who'|'draw'|'crocodile'|'monster'|'story'|'tanks'|'whale'|'alibi'|'race'|'imposter'|'one_pixel'|'roulette';
type Badge={text:string;className:string;customColor?:string};
type Player={id:string;name:string;ready:boolean;host:boolean;score:number;avatar:string;badge:Badge;priority:number};
type Msg={id:string;playerId?:string;name:string;text:string;system?:boolean;at:number;badge?:Badge};
type Answer={id:string;playerId:string;text:string;votes:string[]};
type AnswerGame={mode:'answer';phase:'answering'|'voting'|'results';round:number;maxRounds:number;prompt:string;answers:Answer[]};
type Bluff={id:string;playerId?:string;text:string;votes:string[];truth:boolean};
type BluffGame={mode:'bluff';phase:'answering'|'voting'|'results';round:number;maxRounds:number;question:string;truth:string;answers:Bluff[]};
type Mission={playerId:string;targetId:string;trigger:string;done:boolean};
type TrapGame={mode:'trap';phase:'playing'|'results';round:number;maxRounds:number;endsAt:number;missions:Mission[];completed?:{hunterId:string;targetId:string;trigger:string;message:string}[]};
type WhoGuess={guesserId:string;guessedPlayerId:string};
type WhoAnswer={id:string;playerId:string;text:string;guesses:WhoGuess[]};
type WhoGame={mode:'who';phase:'answering'|'guessing'|'results';round:number;maxRounds:number;prompt:string;answers:WhoAnswer[]};
type DrawEntry={kind:'prompt'|'drawing'|'description';playerId?:string;value:string};
type DrawChain={id:string;entries:DrawEntry[]};
type DrawGame={mode:'draw';phase:'playing'|'results';round:number;maxRounds:number;step:number;maxSteps:number;submitted:string[];chains:DrawChain[];endsAt:number};
type CrocodileGame={mode:'crocodile';phase:'playing'|'results';round:number;maxRounds:number;artistId:string;endsAt:number};
type RaceP={x:number;y:number;vx:number;vy:number;lap:number;checkpoint:number;finishedAt?:number};
type RacePoint={x:number;y:number;width:number;obstacle:boolean};
type RaceGame={mode:'race';phase:'playing'|'results';round:number;maxRounds:number;endsAt:number;countdownEndsAt:number;track:RacePoint[];racers:Record<string,RaceP>;laps:number};
type MonsterPart={kind:'head'|'body'|'legs';playerId:string;value:string};
type MonsterChain={id:string;parts:MonsterPart[]};
type MonsterGame={mode:'monster';phase:'playing'|'results';round:number;maxRounds:number;step:number;submitted:string[];chains:MonsterChain[]};
type StoryEntry={playerId:string;words:string};
type StoryChain={id:string;entries:StoryEntry[]};
type StoryGame={mode:'story';phase:'playing'|'results';round:number;maxRounds:number;step:number;maxSteps:number;submitted:string[];chains:StoryChain[]};
type TankP={x:number;y:number;hp:number;score:number;angle:number;lastShot:number;respawnAt:number;bigUntil:number;smallUntil:number;radialUntil:number};
type TankBullet={id:string;ownerId:string;x:number;y:number;vx:number;vy:number;r:number;damage:number;born:number};
type TankDrop={id:string;x:number;y:number;kind:'big'|'small'|'radial'};
type TanksGame={mode:'tanks';phase:'playing'|'results';round:number;maxRounds:number;endsAt:number;tanks:Record<string,TankP>;bullets:TankBullet[];drops:TankDrop[];nextDropAt:number};
type WhaleP={x:number;alive:boolean;score:number;gap:number};
type WhaleObstacle={id:string;x:number;y:number;w:number;h:number};
type WhaleGame={mode:'whale';phase:'playing'|'results';round:number;maxRounds:number;endsAt:number;startedAt:number;players:Record<string,WhaleP>;obstacles:WhaleObstacle[];nextSpawnAt:number};
type AlibiEvidence={id:string;ownerId:string;text:string;real:boolean;guess?:boolean};
type AlibiGame={mode:'alibi';phase:'playing'|'guessing'|'results';round:number;maxRounds:number;accusedId:string;charge:string;alibi:string[];evidence:AlibiEvidence[];endsAt:number};
type ImposterResult={caughtId?:string;imposterId:string;normalWord:string;imposterWord:string;lastGuess?:string;lastGuessCorrect?:boolean;voteCounts:Record<string,number>};
type ImposterGame={mode:'imposter';phase:'word_reveal'|'associations'|'voting'|'last_chance'|'results';round:number;maxRounds:number;category:string;turnOrder:string[];currentTurnIndex:number;associations:Record<string,string>;voted:string[];revealEndsAt?:number;endsAt?:number;caughtId?:string;imposterResult?:ImposterResult};
type OnePixelResult={saboteurId?:string;task?:string;voteCounts:Record<string,number>;picked?:string};
type OnePixelGame={mode:'one_pixel';phase:'theme_reveal'|'drawing'|'voting'|'results';round:number;maxRounds:number;currentMeme:string;revealEndsAt?:number;endsAt?:number;voted:string[];onePixelResult?:OnePixelResult};
type Game=AnswerGame|BluffGame|TrapGame|WhoGame|DrawGame|CrocodileGame|RaceGame|MonsterGame|StoryGame|TanksGame|WhaleGame|AlibiGame|ImposterGame|OnePixelGame;
type MCDim='overworld'|'nether'|'end';
type MCTool='hand'|'wood_pick'|'stone_pick'|'iron_pick'|'diamond_pick'|'stone_sword'|'iron_sword'|'diamond_sword'|'hoe'|'flint_steel';
type MCPlayer={x:number;y:number;hp:number;hunger:number;inv:Record<string,number>;tool:MCTool;dim:MCDim};
type MCMob={id:string;kind:'zombie'|'pig'|'cow'|'enderman'|'blaze';x:number;y:number;hp:number;dim:MCDim;breed?:number};
type Minecraft={seed:number;blocks:Record<string,string>;players:Record<string,MCPlayer>;mobs:MCMob[];grown:Record<string,number>;fortress:{x:number;y:number};endPortalEyes:number;dragonHp:number;dragonDead:boolean};
type GtaWeapon='pistol'|'rifle'|'rocket'|'grenade'|'drone';
type GtaP={x:number;y:number;hp:number;score:number;weapon:GtaWeapon;owned:GtaWeapon[];vehicleId?:string;lastShot:number;respawnAt:number;angle:number};
type GtaVehicle={id:string;kind:'car'|'bike'|'tank';x:number;y:number;hp:number;driverId?:string;angle:number};
type GtaShot={id:string;ownerId:string;kind:GtaWeapon|'cannon';x:number;y:number;vx:number;vy:number;born:number;explodeAt?:number};
type GtaPickup={id:string;kind:GtaWeapon;x:number;y:number};
type GTA={players:Record<string,GtaP>;vehicles:GtaVehicle[];shots:GtaShot[];pickups:GtaPickup[]};
type Room={code:string;players:Player[];queue:Player[];messages:Msg[];selectedMode:Mode;game?:Game;lastMode?:Exclude<Mode,'roulette'>;finalStandings?:Player[];paused?:boolean;pausedAt?:number;skipVotes?:string[];minecraft?:Minecraft;gta?:GTA;whoPromptHistory?:string[]};

const app=express();app.use(cors());app.use(express.json());
const http=createServer(app);const io=new Server(http,{cors:{origin:'*'},maxHttpBufferSize:2_000_000});const rooms=new Map<string,Room>();
const MAX_PLAYERS=10;
const crocodileWords=new Map<string,string>();
const CROCODILE_WORDS=['кот','вертолет','пицца','космонавт','мороженое','трактор','радуга','пальма','гитара','замок','солнце','компьютер','остров','пират','маяк','черепаха','вулкан','молния','телефон','корона','ножницы','арбуз','призрак','парашют','панда','акула','рыцарь','ракета','телевизор','алмаз','динозавр','кактус','снежинка','костер','самолет','мост','велосипед','викинг','поезд','аквариум','корабль','фонтан','робот','микрофон','бургер','яблоко','часы','паук','скейтборд','фонарь','пещера','компас','бабочка','зонт','вишня','ананас','флаг','бинокль','кошелек','магнит','сова','летучая мышь','гриб','бочка','подзорная труба','подводная лодка','сундук','лабиринт','воздушный шар','пушка','барабан','парусник','карандаш','краб','снеговик','карта','подкова','сапог','меч','щит','свеча','зеркало','кристалл','утюг','термос','галстук','очки','глобус','песочные часы','шлем','перо','топор','якорь','свиток','колокол','пустыня','мельница','карусель','скафандр','дельфин'];

type ImposterSecret={imposterId:string;normalWord:string;imposterWord:string;votes:Record<string,string>};
type OnePixelSecret={saboteurId?:string;task:string;votes:Record<string,string>;lastDrawAt:Record<string,number>};
const imposterSecrets=new Map<string,ImposterSecret>();
const onePixelSecrets=new Map<string,OnePixelSecret>();
const IMPOSTER_PAIRS=[
 {category:'ЗАПАХИ',normal:'пук',imposter:'духи'},
 {category:'ЖИДКОСТИ',normal:'моча',imposter:'липтон'},
 {category:'ЕДА',normal:'доширак',imposter:'торт'},
 {category:'НАПИТКИ',normal:'кефир',imposter:'энергетик'},
 {category:'ТРАНСПОРТ',normal:'трактор',imposter:'самокат'},
 {category:'ЖИВОТНЫЕ',normal:'голубь',imposter:'акула'},
 {category:'ОДЕЖДА',normal:'трусы',imposter:'шуба'},
 {category:'ТЕХНИКА',normal:'микроволновка',imposter:'айфон'},
 {category:'МУЗЫКАЛЬНЫЕ ИНСТРУМЕНТЫ',normal:'баян',imposter:'барабаны'},
 {category:'ПРЕДМЕТЫ В КОМНАТЕ',normal:'унитаз',imposter:'люстра'},
 {category:'СПОРТ',normal:'шахматы',imposter:'бокс'},
 {category:'РАБОТА',normal:'сварщик',imposter:'стоматолог'},
 {category:'МЕСТА',normal:'кладбище',imposter:'аквапарк'},
 {category:'ПОГОДА',normal:'метель',imposter:'жара'},
 {category:'ИНТЕРНЕТ',normal:'капча',imposter:'мем'},
 {category:'ИГРЫ',normal:'майнкрафт',imposter:'тетрис'},
 {category:'ЗВУКИ',normal:'храп',imposter:'сирена'},
 {category:'ВЕЩИ В РЮКЗАКЕ',normal:'учебник',imposter:'банан'},
 {category:'КУХНЯ',normal:'сковородка',imposter:'холодильник'},
 {category:'ЖИВОТНЫЕ ДОМА',normal:'кот',imposter:'таракан'}
];
const ONE_PIXEL_THEMES=['кот на собеседовании','школьный компьютер будущего','рыцарь в супермаркете','акула на велосипеде','учитель на Марсе','пельмень-супергерой','грустный трактор','робот в бане','голубь-мафиози','динозавр в маршрутке','король шаурмы','космонавт на даче'];
const ONE_PIXEL_TASKS=['незаметно добавь персонажу усы','сделай одному объекту лишний глаз','добавь маленький подозрительный огонь','искази колёса или ноги','дорисуй нелепую корону','добавь хвост не тому объекту','преврати один предмет в банан','дорисуй где-нибудь крошечный унитаз'];
app.get('/health',(_req,res)=>res.json({ok:true,rooms:rooms.size}));
function clean(v:any,max:number){return String(v??'').trim().slice(0,max)}
function makeCode(){for(let i=0;i<900;i++){const code=String(100+Math.floor(Math.random()*900));if(!rooms.has(code))return code}throw new Error('Нет свободных кодов комнат')}
function emit(r:Room){io.to(r.code).emit('room:state',r)}
function sys(r:Room,text:string){const m:Msg={id:crypto.randomUUID(),name:'Система',text,system:true,at:Date.now()};r.messages.push(m);r.messages=r.messages.slice(-100);io.to(r.code).emit('chat:new',m)}
function badgeForName(name:string){const cleanName=name.trim().toLocaleLowerCase('ru');if(cleanName==='blagin'||cleanName==='благин')return{badge:{text:'Босс',className:'badge-boss'},priority:1};if(['саша','саня','александр'].includes(cleanName))return{badge:{text:'Спонсор 12р',className:'badge-sponsor-12'},priority:2};if(cleanName==='филатов')return{badge:{text:'Спонсор 10р',className:'badge-sponsor-10'},priority:3};return{badge:{text:'Игрок',className:'badge-default'},priority:99}}
function updateQueuePositions(r:Room){r.queue.sort((a,b)=>a.priority-b.priority);r.queue.forEach((p,i)=>io.to(p.id).emit('room:queued',{position:i+1,code:r.code}))}
function processQueue(r:Room){if(r.game||r.minecraft||r.gta){updateQueuePositions(r);emit(r);return}while(r.players.length<MAX_PLAYERS&&r.queue.length){r.queue.sort((a,b)=>a.priority-b.priority);const p=r.queue.shift()!;const sock=io.sockets.sockets.get(p.id);if(!sock)continue;p.host=r.players.length===0;r.players.push(p);sock.join(r.code);sock.data.code=r.code;delete sock.data.queueCode;io.to(p.id).emit('room:queueJoined',{code:r.code});sys(r,`${p.name} вошёл из очереди.`)}updateQueuePositions(r);emit(r)}
function resetReady(r:Room){r.players.forEach(p=>p.ready=false)}
function resetRoundControls(r:Room){r.skipVotes=[];r.paused=false;r.pausedAt=undefined}
function timedRemaining(r:Room){const g=r.game as any;return g?.endsAt?Math.max(0,g.endsAt-Date.now()):0}
function scheduleCheck(r:Room,kind:'trap'|'alibi-play'|'alibi-guess',round:number){setTimeout(()=>{const g=r.game as any;if(!g||g.round!==round)return;if(r.paused)return scheduleCheck(r,kind,round);const left=timedRemaining(r);if(left>0)return setTimeout(()=>scheduleCheck(r,kind,round),Math.min(left+20,500));if(kind==='trap'&&g.mode==='trap'&&g.phase==='playing')finishTrap(r);if(kind==='alibi-play'&&g.mode==='alibi'&&g.phase==='playing')beginAlibiGuessing(r,round);if(kind==='alibi-guess'&&g.mode==='alibi'&&g.phase==='guessing')finishAlibi(r,round)},250)}

const answerPrompts=['Худшая фраза, которую можно услышать от хирурга перед наркозом: ______','Самая бесполезная функция нового телефона: ______','Настоящая причина, почему преподаватель задержался на пару: ______','Что никогда не стоит писать в резюме: ______','Самое подозрительное объявление на Avito: ______','Что точно не должен говорить пилот перед взлётом: ______'];
const bluffQuestions=[{q:'Как называется боязнь длинных слов?',a:'Гиппопотомонстросескиппедалофобия'},{q:'Какой продукт археологи находили в древнеегипетских гробницах всё ещё пригодным в пищу?',a:'Мёд'},{q:'Какое животное имеет отпечатки пальцев, очень похожие на человеческие?',a:'Коала'},{q:'Как называется точка на поверхности Земли, противоположная другой точке?',a:'Антипод'},{q:'Какой металл при комнатной температуре остаётся жидким?',a:'Ртуть'},{q:'Как называется символ &?',a:'Амперсанд'}];
const trapWords=['да','нет','зачем','ладно','окей','что','почему','когда','где','можно'];
const whoPeople=['директор школы','охранник супермаркета','учитель физкультуры','сосед сверху','таксист','продавец шаурмы','врач','полицейский','ведущий новостей','стример','курьер','повар','президент','космонавт','пилот','машинист метро','сантехник','программист','диджей','футболист','библиотекарь','парикмахер','кассир','строитель','фокусник','фотограф','тренер','геймер','блогер','рыбак','фермер','робот','инопланетянин','пират','рыцарь','детектив','учёный','миллиардер','дворник','директор цирка'];
const whoPlaces=['в школе','на вокзале','в метро','в магазине','в больнице','в лесу','на крыше','в лифте','на свадьбе','на экзамене','в аэропорту','в автобусе','в компьютерном клубе','в банке','на пляже','на Луне','в зоопарке','на стройке','в библиотеке','в столовой','в спортзале','в музее','на концерте','на футбольном матче','в полиции','в парикмахерской','в отеле','в торговом центре','в гараже','на заправке','в аквапарке','в цирке','в кинотеатре','на необитаемом острове','в подвале','в космосе','на уроке','на собеседовании','в очереди к врачу','на родительском собрании'];
const whoObjects=['трактор','холодильник','доширак','арбуз','ноутбук','огнетушитель','самокат','микроволновку','диван','принтер','кактус','палатку','бензопилу','ванну','манекен','телевизор','мешок картошки','генератор','велосипед','шкаф','аквариум','пылесос','барабан','лестницу','тележку','матрас','роутер','чайник','шлем','резиновую утку','пиццу','сейф','лопату','гирю','клавиатуру','костюм банана','корону','дорожный знак','газонокосилку','картонную коробку'];
const whoConditions=['если тебе дадут миллион рублей','если пропадёт интернет','если начнётся зомби-апокалипсис','если тебя назначат директором','если ты проснёшься невидимым','если отменят все правила','если останешься один в городе','если тебе нельзя будет врать','если ты попадёшь в прошлое','если ты попадёшь в будущее','если за тобой будет гнаться гусь','если у тебя останется 100 рублей','если тебя покажут по телевизору','если ты станешь знаменитым','если все телефоны исчезнут','если ты выиграешь спор','если тебя запрут в школе ночью','если тебе дадут суперсилу','если ты сможешь читать мысли','если ты станешь котом на день','если весь день нельзя будет говорить','если придётся жить в магазине неделю','если ты найдёшь чемодан денег','если тебя позовут в космос','если ты станешь учителем','если твой будильник заговорит','если все вокруг уснут','если начнётся эвакуация','если ты случайно станешь мэром','если тебе разрешат украсть одну вещь','если можно будет отменить один закон','если ты застрянешь в лифте','если тебя перепутают со знаменитостью','если тебе дадут танк','если ты найдёшь портал','если исчезнет электричество','если тебя вызовут к директору','если появится клон тебя','если твой питомец начнёт говорить','если завтра конец света'];
const whoTemplates=[
 (i:number)=>`Что ты первым делом сделаешь, ${whoConditions[i]}?`,
 (i:number)=>`Какую самую тупую причину можно придумать, чтобы ${whoPeople[i]} оказался ${whoPlaces[(i+7)%40]}?`,
 (i:number)=>`Что бы ты точно не хотел услышать от человека, который работает как ${whoPeople[i]}?`,
 (i:number)=>`Зачем нормальному человеку может срочно понадобиться ${whoObjects[i]} ${whoPlaces[(i+13)%40]}?`,
 (i:number)=>`Как бы ты объяснил родителям, почему у тебя дома внезапно появился ${whoObjects[i]}?`,
 (i:number)=>`Какое правило ты бы ввёл ${whoPlaces[i]}, если бы мог делать что угодно?`,
 (i:number)=>`Что самое подозрительное мог бы сказать ${whoPeople[i]} ${whoPlaces[(i+19)%40]}?`,
 (i:number)=>`Какой самый нелепый план спасения ты придумаешь, ${whoConditions[(i+5)%40]}?`
];
function generateWhoPrompt(r:Room){r.whoPromptHistory??=[];for(let tries=0;tries<80;tries++){const i=Math.floor(Math.random()*40),t=Math.floor(Math.random()*whoTemplates.length),q=whoTemplates[t](i);if(!r.whoPromptHistory.includes(q)){r.whoPromptHistory.push(q);r.whoPromptHistory=r.whoPromptHistory.slice(-80);return q}}return whoTemplates[Math.floor(Math.random()*whoTemplates.length)](Math.floor(Math.random()*40))}
const drawPrompts=[
 'Кот пытается списать контрольную','Гусь работает охранником в магазине','Преподаватель едет на паре верхом на принтере','Шаурма сбегает от покупателя','Два голубя делят последний доширак','Человек объясняет банкомату, что денег нет','Хомяк проходит собеседование на работу','Скелет опоздал на автобус',
 'Пингвин чинит компьютер феном','Бабушка участвует в гонках на офисном кресле','Голубь требует вернуть ему долг','Крокодил сдаёт экзамен по информатике','Директор прячется в коробке из-под принтера','Кот проводит родительское собрание','Рыцарь заказывает шаурму через терминал','Инопланетянин пытается пройти школьную вахту','Гусь угоняет автобус','Сантехник сражается с Wi-Fi роутером','Хомяк управляет огромным экскаватором','Скелет делает селфи на паспорт','Капибара работает системным администратором','Пират пишет контрольную по Excel','Голубь выступает на деловой конференции','Кот продаёт подозрительный ноутбук на рынке','Бабушка играет в киберспортивном турнире','Динозавр ждёт маршрутку под дождём','Робот жарит пельмени утюгом','Преподаватель пытается поймать сбежавшую клавиатуру','Пингвин несёт холодильник на девятый этаж','Клоун ремонтирует сервер молотком','Гусь проходит паспортный контроль','Кот открывает шаурмичную на Луне','Человек спорит с кофейным автоматом','Капибара сдаёт зачёт вместо студента','Рыцарь пытается подключиться к школьному Wi-Fi','Инопланетянин покупает доширак ночью','Бабушка взламывает банкомат ложкой','Скелет работает курьером','Голубь защищает диплом','Пингвин устраивается водителем автобуса','Кот пытается спрятать трактор','Хомяк проводит урок физкультуры','Директор школы застрял в автомате с едой','Робот просит списать домашнее задание','Крокодил играет свадьбу в компьютерном клубе','Пират ищет клад в кабинете информатики','Капибара убегает от контролёра','Гусь торгуется за видеокарту','Скелет пытается открыть дверь отпечатком пальца','Кот вызывает такси для холодильника','Бабушка чинит спутник на крыше школы','Голубь работает судьёй на футбольном матче','Пингвин крадётся по библиотеке с бензопилой','Рыцарь защищает последний доширак','Хомяк руководит строительством небоскрёба','Динозавр сидит за первой партой','Инопланетянин фотографируется на студенческий','Капибара объясняет полиции, откуда у неё трактор'
];

// Конструктор тем для Фоторобота. Все элементы уже записаны в форме,
// в которой их можно безопасно склеить без сложного склонения слов.
const drawSubjects=[
 'Кот','Гусь','Голубь','Хомяк','Капибара','Пингвин','Крокодил','Динозавр','Скелет','Робот',
 'Инопланетянин','Пират','Рыцарь','Клоун','Бабушка','Дед','Преподаватель','Директор школы','Студент','Охранник',
 'Курьер','Сантехник','Программист','Таксист','Повар','Полицейский','Космонавт','Археолог','Фокусник','Вампир',
 'Зомби','Снеговик','Ниндзя','Ковбой','Шпион','Викинг','Гном','Волшебник','Медведь','Енот',
 'Жираф','Акула на ножках','Краб','Лягушка','Петух','Собака','Коза','Черепаха','Офисный менеджер','Человек в костюме банана'
];
const drawActions=[
 'чинит','крадёт','прячет','покупает','продаёт','тащит','рисует','фотографирует','ремонтирует','ломает',
 'запускает','догоняет','спасает','выгуливает','допрашивает','обнимает','кормит','будит','моет','готовит',
 'закапывает','распаковывает','собирает','охраняет','ищет','ловит','учит','вызывает','арендует','выбрасывает',
 'заряжает','взвешивает','красит','подписывает','прячет от полиции','пытается продать','пытается съесть','пытается починить','пытается украсть','пытается приручить',
 'несёт на голове','катается верхом на','устраивает драку с','играет в шахматы с','ведёт переговоры с','снимает видео про','заказывает доставку для','строит дом для','проводит собеседование с','объясняет математику для'
];
const drawObjects=[
 'принтер','холодильник','трактор','роутер','школьный компьютер','огромный доширак','шаурму','банкомат','офисное кресло','клавиатуру',
 'мышку','проектор','микроволновку','автобус','самокат','телевизор','пылесос','чайник','унитаз','арбуз',
 'гигантский носок','чемодан денег','мешок картошки','резиновую утку','дорожный знак','спутник','ракету','аквариум','кактус','торговый автомат',
 'огромную ложку','бочку компота','серверную стойку','дверь от машины','палатку','скелет динозавра','коробку пельменей','золотой батон','робота-пылесоса','пачку контрольных',
 'гусеницу экскаватора','мешок клавиатур','игровой автомат','памятник голубю','подводную лодку','надувной бассейн','барабан','генератор','мешок цемента','тележку из супермаркета'
];
const drawCircumstances=[
 'во время контрольной','посреди урока','на крыше школы','в компьютерном клубе','в переполненном автобусе','на свадьбе','на похоронах','в супермаркете','на футбольном поле','в библиотеке',
 'в лифте','на Луне','на необитаемом острове','в кабинете директора','под проливным дождём','в три часа ночи','во время экзамена','на сцене перед толпой','на парковке','в школьной столовой',
 'на вокзале','в аэропорту','в метро','на пляже','в лесу','в пустыне','на Северном полюсе','в космосе','в средневековом замке','в аквапарке',
 'на родительском собрании','во время прямого эфира','на деловой встрече','на уроке физкультуры','в очереди к врачу','на выпускном','во время эвакуации','на секретной военной базе','на дне океана','в зоопарке',
 'на стройке','в музее','в цирке','в отделении полиции','в банке','на заправке','в парикмахерской','на экзамене по вождению','в огромной пробке','на школьной линейке'
];
const drawModifiers=[
 'с закрытыми глазами','одной рукой','стоя на одной ноге','пока все вокруг спят','пока за ним гонится охрана','делая вид, что всё нормально','в костюме банана','в полной темноте','под громкую музыку','с очень серьёзным лицом',
 'не выпуская из рук телефон','с кастрюлей на голове','верхом на офисном кресле','используя только ложку','без обуви','в огромных солнцезащитных очках','под наблюдением полиции','пока рядом снимают репортаж','с инструкцией вверх ногами','вместе с тремя голубями',
 'потому что проиграл спор','потому что так написано в инструкции','потому что опаздывает','потому что ему заплатили 100 рублей','потому что другого плана нет','потому что интернет отключили','потому что дверь заперта','потому что это часть экзамена','потому что за ним следят','потому что он уверен, что так и надо',
 'на глазах у директора','под аплодисменты толпы','с секундомером в зубах','в резиновых сапогах','с плакатом «Я всё контролирую»','не переставая танцевать','пытаясь не разбудить кота','во время видеозвонка','с фонариком вместо микрофона','в сопровождении оркестра',
 'с завязанными глазами','сидя в детской коляске','в противогазе','под звуки пожарной сигнализации','с огромным рюкзаком','притворяясь сотрудником магазина','пока вокруг летают бумажки','с короной на голове','в окружении десяти уток','как будто от этого зависит судьба мира'
];
function randomOf<T>(xs:T[]){return xs[Math.floor(Math.random()*xs.length)]}
function generateDrawPrompt(){return `${randomOf(drawSubjects)} ${randomOf(drawActions)} ${randomOf(drawObjects)} ${randomOf(drawCircumstances)} ${randomOf(drawModifiers)}`}
function makeDrawPrompts(count:number){const out:string[]=[];const seen=new Set<string>();while(out.length<count){const useManual=Math.random()<0.28;const prompt=useManual?randomOf(drawPrompts):generateDrawPrompt();if(!seen.has(prompt)){seen.add(prompt);out.push(prompt)}}return out}

const alibiCases=[
 {charge:'украл все мышки из кабинета информатики',alibi:['В 19:30 ты зашёл в магазин.','Ты был там один.','Купил арбуз и воду.','Вышел в 20:05.'],real:['Чек из магазина пробит в 19:47.','Камера магазина сняла тебя без компании.','На банковской карте есть покупка воды в 19:48.'],fake:['Магазин закрылся ещё в 18:00.','Камера школы сняла тебя в кабинете в 19:40.','Продавец утверждает, что ты покупал отвёртку.']},
 {charge:'продал школьный проектор на Avito',alibi:['С 17:00 до 18:00 ты был в компьютерном клубе.','Ты пришёл туда с Димой.','Платил наличными.','Домой ушёл пешком.'],real:['Администратор клуба помнит тебя около 17:20.','Дима подтвердил, что пришёл вместе с тобой.','Камера у клуба сняла тебя в 17:54.'],fake:['На твоей карте есть оплата такси в 17:15.','Дима заявил, что весь день тебя не видел.','Покупатель проектора назвал твоё имя.']},
 {charge:'съел чужой доширак и подделал алиби',alibi:['Во время пропажи ты сидел в библиотеке.','С собой у тебя был только чай.','Ты ушёл оттуда в 14:10.','До библиотеки ты пришёл на автобусе.'],real:['Библиотекарь видел тебя за столом.','Проездной отмечен в автобусе в 12:58.','Камера выхода показывает тебя в 14:09.'],fake:['В мусорке нашли упаковку с твоими отпечатками.','Библиотека в тот день была закрыта.','Камера столовой сняла тебя с дошираком.']},
 {charge:'ночью переставил все клавиши на школьных клавиатурах',alibi:['В 23:00 ты уже был дома.','Ты играл за компьютером.','С тобой в Discord сидел друг.','Из дома после 22:30 ты не выходил.'],real:['Друг подтвердил звонок в Discord в 23:12.','Домашний роутер зафиксировал твой компьютер онлайн.','Камера подъезда не показывает твоего выхода после 22:30.'],fake:['Твой пропуск использовали в школе в 23:18.','Таксист узнал тебя по фотографии.','На одной клавиатуре нашли твою записку.']}
];
const realModes:Exclude<Mode,'roulette'>[]=['answer','bluff','trap','who','draw','crocodile','monster','story','tanks','whale','alibi','race','imposter','one_pixel'];
function chooseRoulette(r:Room){const pool=realModes.filter(x=>x!==r.lastMode);return pool[Math.floor(Math.random()*pool.length)]||'answer'}
function modeName(m:Exclude<Mode,'roulette'>){return m==='answer'?'Ответь как еблан':m==='bluff'?'Хуй знает':m==='trap'?'Подстава':m==='who'?'Кто это написал?':m==='draw'?'Фоторобот':m==='crocodile'?'Крокодил':m==='monster'?'Сын пробирки':m==='story'?'Продолжи историю':m==='tanks'?'Танчики':m==='whale'?'Беги от кита':m==='race'?'Гонки':m==='imposter'?'Самозванец':m==='one_pixel'?'Один пиксель':'Алиби'}
function startGame(r:Room){resetReady(r);r.finalStandings=undefined;const chosen=r.selectedMode==='roulette'?chooseRoulette(r):r.selectedMode;r.lastMode=chosen;if(r.selectedMode==='roulette')sys(r,`Рулетка выбрала режим: ${modeName(chosen)}.`);if(chosen==='answer')startAnswer(r,1);else if(chosen==='bluff')startBluff(r,1);else if(chosen==='trap')startTrap(r,1);else if(chosen==='who')startWho(r,1);else if(chosen==='draw')startDraw(r,1);else if(chosen==='crocodile')startCrocodile(r);else if(chosen==='monster')startMonster(r);else if(chosen==='story')startStory(r);else if(chosen==='tanks')startTanks(r);else if(chosen==='whale')startWhale(r);else if(chosen==='race')startRace(r);else if(chosen==='imposter')startImposter(r,1);else if(chosen==='one_pixel')startOnePixel(r);else startAlibi(r,1)}
function startAnswer(r:Room,round:number){resetRoundControls(r);r.game={mode:'answer',phase:'answering',round,maxRounds:3,prompt:answerPrompts[(round-1)%answerPrompts.length],answers:[]};sys(r,`Раунд ${round} начался.`);emit(r)}
function startBluff(r:Room,round:number){resetRoundControls(r);const x=bluffQuestions[(round-1)%bluffQuestions.length];r.game={mode:'bluff',phase:'answering',round,maxRounds:3,question:x.q,truth:x.a,answers:[]};sys(r,`Раунд ${round} начался.`);emit(r)}
function startWho(r:Room,round:number){resetRoundControls(r);r.game={mode:'who',phase:'answering',round,maxRounds:3,prompt:generateWhoPrompt(r),answers:[]};sys(r,`Кто это написал?: раунд ${round}.`);emit(r)}
const DRAW_TIMEOUT=60_000;const BLANK_DRAWING='data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI3MDAiIGhlaWdodD0iNDMwIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjZjVmMGRmIi8+PHRleHQgeD0iNTAlIiB5PSI1MCUiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM3NzciIGZvbnQtc2l6ZT0iMzIiPtCd0LUg0YPRgdC/0LXQuzwvdGV4dD48L3N2Zz4=';
function scheduleDrawTimeout(r:Room,g:DrawGame){const round=g.round,step=g.step,endsAt=g.endsAt;setTimeout(()=>{const cur=r.game;if(!cur||cur.mode!=='draw'||cur.phase!=='playing'||cur.round!==round||cur.step!==step||cur.endsAt!==endsAt)return;if(Date.now()<cur.endsAt)return scheduleDrawTimeout(r,cur);for(const p of r.players){if(cur.submitted.includes(p.id))continue;const task=drawTask(r,cur,p.id);if(!task)continue;const chain=cur.chains.find(c=>c.id===task.chainId);if(!chain)continue;chain.entries.push({kind:task.kind as 'drawing'|'description',playerId:p.id,value:task.kind==='drawing'?BLANK_DRAWING:'Не успел'});cur.submitted.push(p.id)}advanceDraw(r,cur)},Math.max(20,endsAt-Date.now()+20))}
function startDraw(r:Room,round:number){resetRoundControls(r);const prompts=makeDrawPrompts(r.players.length);const chains:DrawChain[]=r.players.map((p,i)=>({id:crypto.randomUUID(),entries:[{kind:'prompt' as const,value:prompts[i]}]}));r.game={mode:'draw',phase:'playing',round,maxRounds:2,step:0,maxSteps:Math.max(3,Math.min(5,r.players.length)),submitted:[],chains,endsAt:Date.now()+DRAW_TIMEOUT};sys(r,`Фоторобот: раунд ${round}. На каждый этап 60 секунд.`);scheduleDrawTimeout(r,r.game);emit(r)}
function drawTask(r:Room,g:DrawGame,playerId:string){const idx=r.players.findIndex(p=>p.id===playerId);if(idx<0)return null;const chain=g.chains[(idx-g.step%r.players.length+r.players.length)%r.players.length];const last=chain.entries[chain.entries.length-1];return{chainId:chain.id,kind:g.step%2===0?'drawing':'description',source:last}}
function advanceDraw(r:Room,g:DrawGame){if(g.submitted.length<r.players.length)return;const round=g.round,step=g.step;setTimeout(()=>{const cur=r.game;if(!cur||cur.mode!=='draw'||cur.phase!=='playing'||cur.round!==round||cur.step!==step||cur.submitted.length<r.players.length)return;cur.submitted=[];cur.step++;if(cur.step>=cur.maxSteps){cur.phase='results';emit(r);return}cur.endsAt=Date.now()+DRAW_TIMEOUT;scheduleDrawTimeout(r,cur);emit(r)},2500)}
function beginCrocodileRound(r:Room,artistId:string){const g=r.game;if(!g||g.mode!=='crocodile')return;g.artistId=artistId;g.endsAt=Date.now()+60_000;const word=CROCODILE_WORDS[Math.floor(Math.random()*CROCODILE_WORDS.length)];crocodileWords.set(r.code,word);io.to(r.code).emit('crocodile:clear');io.to(artistId).emit('crocodile:word',{word});sys(r,`Крокодил: раунд ${g.round}/${g.maxRounds}. Рисует ${r.players.find(p=>p.id===artistId)?.name||'игрок'}.`);emit(r);const round=g.round,endsAt=g.endsAt;setTimeout(()=>{const cur=r.game;if(!cur||cur.mode!=='crocodile'||cur.phase!=='playing'||cur.round!==round||cur.endsAt!==endsAt)return;advanceCrocodile(r)},60_050)}
function startCrocodile(r:Room){resetRoundControls(r);const artist=r.players[Math.floor(Math.random()*r.players.length)]?.id;if(!artist)return;r.game={mode:'crocodile',phase:'playing',round:1,maxRounds:4,artistId:artist,endsAt:Date.now()+60_000};r.players.forEach(p=>p.score=0);beginCrocodileRound(r,artist)}
function advanceCrocodile(r:Room,winnerId?:string){const g=r.game;if(!g||g.mode!=='crocodile'||g.phase!=='playing')return;crocodileWords.delete(r.code);if(g.round>=g.maxRounds){g.phase='results';sys(r,'Крокодил закончен.');emit(r);return}const ids=r.players.map(p=>p.id);const current=ids.indexOf(g.artistId);g.round++;const next=winnerId&&ids.includes(winnerId)?winnerId:ids[(current+1+ids.length)%ids.length];beginCrocodileRound(r,next)}
function generateRaceTrack(){const variants=[[[140,310],[150,150],[300,90],[520,95],[760,110],[880,220],[860,430],[700,520],[450,525],[230,500],[120,400],[140,310]],[[150,310],[190,130],[400,100],[500,220],[600,100],[820,150],[880,310],[820,480],[610,510],[500,390],[390,510],[180,470],[120,350],[150,310]],[[130,330],[170,150],[360,100],[560,145],[790,100],[900,260],[820,420],[620,500],[430,440],[240,520],[100,410],[130,330]]];const pts=variants[Math.floor(Math.random()*variants.length)];return pts.map((q,i)=>({x:q[0],y:q[1],width:150,obstacle:i>1&&i<pts.length-2&&Math.random()>.72}))}
function raceDistToTrack(track:RacePoint[],x:number,y:number){let best=Infinity;for(let i=0;i<track.length-1;i++){const a=track[i],b=track[i+1],vx=b.x-a.x,vy=b.y-a.y,l2=vx*vx+vy*vy||1,t=Math.max(0,Math.min(1,((x-a.x)*vx+(y-a.y)*vy)/l2)),px=a.x+t*vx,py=a.y+t*vy;best=Math.min(best,Math.hypot(x-px,y-py))}return best}
function startRace(r:Room){resetRoundControls(r);const track=generateRaceTrack(),racers:Record<string,RaceP>={};r.players.forEach((p,i)=>racers[p.id]={x:track[0].x-12,y:track[0].y-32+i*15,vx:0,vy:0,lap:0,checkpoint:1});r.game={mode:'race',phase:'playing',round:1,maxRounds:1,endsAt:Date.now()+120_000,countdownEndsAt:Date.now()+3_000,track,racers,laps:1};sys(r,'Гонки: старт через 3 секунды. Ехать можно только по трассе — контрольные точки не дают срезать маршрут.');emit(r);setTimeout(()=>{const g=r.game;if(g?.mode==='race'&&g.phase==='playing'){g.phase='results';emit(r)}},120_100)}
function startMonster(r:Room){resetRoundControls(r);r.game={mode:'monster',phase:'playing',round:1,maxRounds:1,step:0,submitted:[],chains:r.players.map(()=>({id:crypto.randomUUID(),parts:[]}))};sys(r,'Сын пробирки: сначала головы, затем чужие тела, затем чужие ноги.');emit(r)}
function monsterTask(r:Room,g:MonsterGame,playerId:string){const idx=r.players.findIndex(p=>p.id===playerId);if(idx<0)return null;const chain=g.chains[(idx-g.step%r.players.length+r.players.length)%r.players.length];return chain}
function advanceMonster(r:Room,g:MonsterGame){if(g.submitted.length<r.players.length)return;const step=g.step;setTimeout(()=>{const cur=r.game;if(!cur||cur.mode!=='monster'||cur.phase!=='playing'||cur.step!==step||cur.submitted.length<r.players.length)return;cur.submitted=[];cur.step++;if(cur.step>=3)cur.phase='results';emit(r)},2500)}
function startStory(r:Room){resetRoundControls(r);r.game={mode:'story',phase:'playing',round:1,maxRounds:1,step:0,maxSteps:6,submitted:[],chains:r.players.map(()=>({id:crypto.randomUUID(),entries:[]}))};sys(r,'Продолжи историю: каждый пишет ровно два слова, потом цепочка переходит другому игроку.');emit(r)}
function storyTask(r:Room,g:StoryGame,playerId:string){const idx=r.players.findIndex(p=>p.id===playerId);if(idx<0)return null;return g.chains[(idx-g.step%r.players.length+r.players.length)%r.players.length]}
function advanceStory(r:Room,g:StoryGame){if(g.submitted.length<r.players.length)return;g.submitted=[];g.step++;if(g.step>=g.maxSteps)g.phase='results';emit(r)}
const tankWalls=[{x:250,y:150,w:130,h:28},{x:620,y:140,w:28,h:160},{x:430,y:360,w:160,h:28},{x:120,y:390,w:110,h:28},{x:760,y:400,w:110,h:28}];
function tankBlocked(x:number,y:number,radius=18){return tankWalls.some(w=>x+radius>w.x&&x-radius<w.x+w.w&&y+radius>w.y&&y-radius<w.y+w.h)}
function startTanks(r:Room){resetRoundControls(r);const tanks:Record<string,TankP>={};r.players.forEach((p,i)=>{const spots=[[90,90],[910,530],[910,90],[90,530],[500,80],[500,540]];const q=spots[i%spots.length];tanks[p.id]={x:q[0],y:q[1],hp:100,score:0,angle:0,lastShot:0,respawnAt:0,bigUntil:0,smallUntil:0,radialUntil:0}});r.game={mode:'tanks',phase:'playing',round:1,maxRounds:1,endsAt:Date.now()+90000,tanks,bullets:[],drops:[],nextDropAt:Date.now()+5000};sys(r,'Танчики: 90 секунд. WASD — движение, ПКМ — выстрел. Аирдропы дают усиление на 10 секунд.');emit(r)}
function tankBullet(g:TanksGame,ownerId:string,x:number,y:number,ang:number,radius:number,damage:number){g.bullets.push({id:crypto.randomUUID(),ownerId,x,y,vx:Math.cos(ang)*10,vy:Math.sin(ang)*10,r:radius,damage,born:Date.now()})}
function tanksTick(r:Room,g:TanksGame){if(g.phase!=='playing')return;const now=Date.now();if(now>=g.endsAt){for(const [id,t] of Object.entries(g.tanks)){const p=r.players.find(p=>p.id===id);if(p)p.score=t.score}g.phase='results';emit(r);return}if(now>=g.nextDropAt&&g.drops.length<4){g.drops.push({id:crypto.randomUUID(),x:70+Math.random()*860,y:70+Math.random()*460,kind:randomOf(['big','small','radial'] as const)});g.nextDropAt=now+7000+Math.random()*5000}for(const [id,t] of Object.entries(g.tanks)){if(t.hp<=0&&now>=t.respawnAt){const q=[[90,90],[910,530],[910,90],[90,530],[500,80],[500,540]][Math.floor(Math.random()*6)];t.x=q[0];t.y=q[1];t.hp=100}for(const d of [...g.drops])if(Math.hypot(t.x-d.x,t.y-d.y)<30){if(d.kind==='big')t.bigUntil=now+10000;if(d.kind==='small')t.smallUntil=now+10000;if(d.kind==='radial')t.radialUntil=now+10000;g.drops=g.drops.filter(x=>x.id!==d.id)}}for(const b of [...g.bullets]){b.x+=b.vx;b.y+=b.vy;if(now-b.born>4000||b.x<0||b.x>1000||b.y<0||b.y>620||tankBlocked(b.x,b.y,b.r)){g.bullets=g.bullets.filter(x=>x.id!==b.id);continue}for(const [id,t] of Object.entries(g.tanks)){if(id===b.ownerId||t.hp<=0)continue;const rr=(now<t.smallUntil?11:19)+b.r;if(Math.hypot(t.x-b.x,t.y-b.y)<rr){t.hp-=b.damage;g.bullets=g.bullets.filter(x=>x.id!==b.id);if(t.hp<=0){t.hp=0;t.respawnAt=now+3000;const killer=g.tanks[b.ownerId];if(killer)killer.score++}break}}}emit(r)}
function startWhale(r:Room){resetRoundControls(r);const players:Record<string,WhaleP>={};r.players.forEach((p,i)=>players[p.id]={x:.25+(i%4)*.16,alive:true,score:0,gap:.44});r.game={mode:'whale',phase:'playing',round:1,maxRounds:1,endsAt:Date.now()+90000,startedAt:Date.now(),players,obstacles:[],nextSpawnAt:Date.now()+850};sys(r,'Погоня от кита: только влево/вправо. Препятствия несутся от горизонта; если застрял — выбирайся в сторону, пока кит не догнал.');emit(r)}
function whaleTick(r:Room,g:WhaleGame){if(g.phase!=='playing')return;const now=Date.now(),elapsed=(now-g.startedAt)/1000,diff=1+elapsed/24,speed=.0105*diff;if(now>=g.nextSpawnAt){const w=.055+Math.random()*.095;g.obstacles.push({id:crypto.randomUUID(),x:.08+Math.random()*(.84-w),y:.03,w,h:.045+Math.random()*.035});g.nextSpawnAt=now+Math.max(220,820/diff)}for(const o of g.obstacles)o.y+=speed;g.obstacles=g.obstacles.filter(o=>o.y<1.08);for(const p of Object.values(g.players)){if(!p.alive)continue;p.score=Math.floor(elapsed*12);const hit=g.obstacles.some(o=>o.y<.91&&o.y+o.h>.77&&p.x+.026>o.x&&p.x-.026<o.x+o.w);p.gap-=.00034*diff;if(hit)p.gap-=.0052*diff;else p.gap=Math.min(.46,p.gap+.00062);if(p.gap<=.035)p.alive=false}if(now>=g.endsAt||Object.values(g.players).every(p=>!p.alive)){for(const [id,q] of Object.entries(g.players)){const p=r.players.find(p=>p.id===id);if(p)p.score=q.score}g.phase='results'}emit(r)}


function shuffled<T>(items:T[]){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function startImposter(r:Room,round:number){
 resetRoundControls(r);
 const rawPair=IMPOSTER_PAIRS[Math.floor(Math.random()*IMPOSTER_PAIRS.length)],pair=Math.random()<.5?rawPair:{...rawPair,normal:rawPair.imposter,imposter:rawPair.normal};
 const imposter=r.players[Math.floor(Math.random()*r.players.length)];
 const turnOrder=shuffled(r.players.map(p=>p.id));
 const revealEndsAt=Date.now()+5000;
 r.game={mode:'imposter',phase:'word_reveal',round,maxRounds:3,category:pair.category,turnOrder,currentTurnIndex:0,associations:{},voted:[],revealEndsAt};
 imposterSecrets.set(r.code,{imposterId:imposter.id,normalWord:pair.normal,imposterWord:pair.imposter,votes:{}});
 for(const p of r.players)io.to(p.id).emit('imposter:role',{role:p.id===imposter.id?'imposter':'normal',word:p.id===imposter.id?pair.imposter:pair.normal,category:pair.category});
 sys(r,`Самозванец: раунд ${round}. Слова из одной категории, но заметно разные.`);emit(r);
 setTimeout(()=>{const g=r.game;if(!g||g.mode!=='imposter'||g.round!==round||g.phase!=='word_reveal')return;g.phase='associations';g.revealEndsAt=undefined;emit(r)},5100);
}
function finishImposterVoting(r:Room,g:ImposterGame){
 const secret=imposterSecrets.get(r.code);if(!secret)return;
 const counts:Record<string,number>={};for(const target of Object.values(secret.votes))counts[target]=(counts[target]||0)+1;
 const max=Math.max(0,...Object.values(counts));const leaders=Object.entries(counts).filter(([,n])=>n===max).map(([id])=>id);const caughtId=max>0&&leaders.length===1?leaders[0]:undefined;
 g.caughtId=caughtId;
 if(caughtId===secret.imposterId){
  for(const [voter,target] of Object.entries(secret.votes))if(target===secret.imposterId){const p=r.players.find(x=>x.id===voter);if(p)p.score+=200}
  g.phase='last_chance';g.endsAt=Date.now()+30000;emit(r);scheduleImposterLastChance(r,g.round);return;
 }
 const imp=r.players.find(p=>p.id===secret.imposterId);if(imp)imp.score+=500;
 g.phase='results';g.imposterResult={caughtId,imposterId:secret.imposterId,normalWord:secret.normalWord,imposterWord:secret.imposterWord,voteCounts:counts};emit(r);
}
function finishImposterGuess(r:Room,g:ImposterGame,guess:string){
 const secret=imposterSecrets.get(r.code);if(!secret||g.phase!=='last_chance')return;
 const norm=(v:string)=>v.trim().toLocaleLowerCase('ru');const correct=!!guess&&norm(guess)===norm(secret.normalWord);
 if(correct){const imp=r.players.find(p=>p.id===secret.imposterId);if(imp)imp.score+=400}else for(const p of r.players)if(p.id!==secret.imposterId)p.score+=100;
 const counts:Record<string,number>={};for(const target of Object.values(secret.votes))counts[target]=(counts[target]||0)+1;
 g.phase='results';g.endsAt=undefined;g.imposterResult={caughtId:g.caughtId,imposterId:secret.imposterId,normalWord:secret.normalWord,imposterWord:secret.imposterWord,lastGuess:guess,lastGuessCorrect:correct,voteCounts:counts};emit(r);
}
function scheduleImposterLastChance(r:Room,round:number){setTimeout(()=>{const g=r.game;if(!g||g.mode!=='imposter'||g.round!==round||g.phase!=='last_chance')return;if(r.paused)return scheduleImposterLastChance(r,round);const left=(g.endsAt||0)-Date.now();if(left>0)return setTimeout(()=>scheduleImposterLastChance(r,round),Math.min(left+20,500));finishImposterGuess(r,g,'')},350)}

function startOnePixel(r:Room){
 resetRoundControls(r);const currentMeme=ONE_PIXEL_THEMES[Math.floor(Math.random()*ONE_PIXEL_THEMES.length)];
 const hasSaboteur=r.players.length<4||Math.random()>.2;const saboteur=hasSaboteur?r.players[Math.floor(Math.random()*r.players.length)]:undefined;const task=ONE_PIXEL_TASKS[Math.floor(Math.random()*ONE_PIXEL_TASKS.length)];
 r.game={mode:'one_pixel',phase:'theme_reveal',round:1,maxRounds:1,currentMeme,revealEndsAt:Date.now()+5000,voted:[]};
 onePixelSecrets.set(r.code,{saboteurId:saboteur?.id,task,votes:{},lastDrawAt:{}});
 for(const p of r.players)io.to(p.id).emit('one_pixel:role',{saboteur:p.id===saboteur?.id,task:p.id===saboteur?.id?task:undefined});
 sys(r,'Один пиксель: общий рисунок. Один короткий штрих — потом 1,3 секунды перезарядки. После рисунка голосование за вредителя.');emit(r);
 setTimeout(()=>{const g=r.game;if(!g||g.mode!=='one_pixel'||g.phase!=='theme_reveal')return;g.phase='drawing';g.revealEndsAt=undefined;g.endsAt=Date.now()+60000;io.to(r.code).emit('one_pixel:clear');emit(r);scheduleOnePixelEnd(r)},5100);
}
function scheduleOnePixelEnd(r:Room){setTimeout(()=>{const g=r.game;if(!g||g.mode!=='one_pixel'||g.phase!=='drawing')return;if(r.paused)return scheduleOnePixelEnd(r);const left=(g.endsAt||0)-Date.now();if(left>0)return setTimeout(()=>scheduleOnePixelEnd(r),Math.min(left+20,500));beginOnePixelVoting(r)},350)}
function beginOnePixelVoting(r:Room){const g=r.game;if(!g||g.mode!=='one_pixel'||g.phase!=='drawing')return;g.phase='voting';g.endsAt=undefined;r.skipVotes=[];emit(r)}
function finishOnePixelVoting(r:Room,g:OnePixelGame){const secret=onePixelSecrets.get(r.code);if(!secret)return;const counts:Record<string,number>={};for(const target of Object.values(secret.votes))counts[target]=(counts[target]||0)+1;const max=Math.max(0,...Object.values(counts));const leaders=Object.entries(counts).filter(([,n])=>n===max).map(([id])=>id);const picked=max>0&&leaders.length===1?leaders[0]:undefined;const answer=secret.saboteurId||'none';for(const [voter,target] of Object.entries(secret.votes))if(target===answer){const p=r.players.find(x=>x.id===voter);if(p)p.score+=300}if(secret.saboteurId&&picked!==secret.saboteurId){const sab=r.players.find(p=>p.id===secret.saboteurId);if(sab)sab.score+=500}g.phase='results';g.onePixelResult={saboteurId:secret.saboteurId,task:secret.saboteurId?secret.task:undefined,voteCounts:counts,picked};emit(r)}
function sanitizeOnePixelDraw(raw:any){const type=String(raw?.type||'');if(!['brush','eraser','line','rect','circle','triangle'].includes(type))return null;const clamp=(v:any,max:number)=>Math.max(0,Math.min(max,Number(v)||0)),size=Math.max(1,Math.min(40,Number(raw?.size)||6)),color=/^#[0-9a-f]{6}$/i.test(String(raw?.color||''))?String(raw.color):'#111111';if(type==='brush'||type==='eraser'){if(!Array.isArray(raw?.points)||raw.points.length<2)return null;const points=raw.points.slice(0,45).map((q:any)=>({x:clamp(q?.x,800),y:clamp(q?.y,600)}));return{type,points,color:type==='eraser'?'#f5f0df':color,size}}const start={x:clamp(raw?.start?.x,800),y:clamp(raw?.start?.y,600)},end={x:clamp(raw?.end?.x,800),y:clamp(raw?.end?.y,600)};return{type,start,end,color,size}}

function startTrap(r:Room,round:number){resetRoundControls(r);const shuffled=[...trapWords].sort(()=>Math.random()-.5);const missions=r.players.map((p,i)=>{const targets=r.players.filter(x=>x.id!==p.id);const target=targets[Math.floor(Math.random()*targets.length)];return{playerId:p.id,targetId:target.id,trigger:shuffled[i%shuffled.length],done:false}});r.game={mode:'trap',phase:'playing',round,maxRounds:3,endsAt:Date.now()+60000,missions,completed:[]};sys(r,`Подстава: раунд ${round}. У вас 60 секунд.`);emit(r);scheduleCheck(r,'trap',round)}
function finishTrap(r:Room){const g=r.game;if(!g||g.mode!=='trap'||g.phase!=='playing')return;g.phase='results';emit(r)}

function startAlibi(r:Room,round:number){resetRoundControls(r);const accused=r.players[(round-1)%r.players.length];const c=alibiCases[(round-1)%alibiCases.length];const investigators=r.players.filter(p=>p.id!==accused.id);const pool=[...c.real.map(text=>({text,real:true})),...c.fake.map(text=>({text,real:false}))].sort(()=>Math.random()-.5);const evidence=investigators.map((p,i)=>({id:crypto.randomUUID(),ownerId:p.id,...pool[i%pool.length]}));r.game={mode:'alibi',phase:'playing',round,maxRounds:Math.min(3,r.players.length),accusedId:accused.id,charge:c.charge,alibi:c.alibi,evidence,endsAt:Date.now()+45000};sys(r,`Алиби: ${accused.name} под подозрением. Следователи получили улики.`);emit(r);scheduleCheck(r,'alibi-play',round)}
function beginAlibiGuessing(r:Room,round:number){const g=r.game;if(!g||g.mode!=='alibi'||g.round!==round||g.phase!=='playing')return;g.phase='guessing';r.skipVotes=[];g.endsAt=Date.now()+30000;sys(r,'Допрос окончен. Подозреваемый должен определить, какие улики настоящие.');emit(r);scheduleCheck(r,'alibi-guess',round)}
function finishAlibi(r:Room,round:number){const g=r.game;if(!g||g.mode!=='alibi'||g.round!==round||g.phase==='results')return;const accused=r.players.find(p=>p.id===g.accusedId);for(const e of g.evidence){const owner=r.players.find(p=>p.id===e.ownerId);if(e.guess===e.real){if(accused)accused.score+=300}else if(e.guess!==undefined&&owner)owner.score+=400}g.phase='results';emit(r)}

function beginVoting(r:Room){const g=r.game;if(!g||g.phase!=='answering'||g.mode==='who')return;if(g.mode==='bluff')g.answers.push({id:crypto.randomUUID(),text:g.truth,votes:[],truth:true});g.phase='voting';emit(r)}
function finishVoting(r:Room){const g=r.game;if(!g||(g.mode!=='answer'&&g.mode!=='bluff')||g.phase!=='voting')return;if(g.mode==='answer'){for(const a of g.answers){const owner=r.players.find(p=>p.id===a.playerId);if(owner)owner.score+=a.votes.length*100}}else{for(const a of g.answers){if(a.truth){for(const voter of a.votes){const p=r.players.find(x=>x.id===voter);if(p)p.score+=1000}}else if(a.playerId){const owner=r.players.find(p=>p.id===a.playerId);if(owner)owner.score+=a.votes.length*500}}}g.phase='results';emit(r)}
function totalVotes(g:AnswerGame|BluffGame){return g.answers.reduce((n,a)=>n+a.votes.length,0)}
function finishGame(r:Room){r.finalStandings=[...r.players].sort((a,b)=>b.score-a.score).map(p=>({...p}));r.game=undefined;imposterSecrets.delete(r.code);onePixelSecrets.delete(r.code);resetReady(r);sys(r,'Игра закончена.');processQueue(r)}

function normalizeName(raw:any){const n=clean(raw,20)||'Игрок';return n.toLocaleLowerCase('ru')==='ефим'?'петух':n}
const avatars=['😎','🤡','🐸','🐱','🐶','🦆','🐧','🦝','🗿','👽','🤖','💀','🧙','🥸','🐔'];
function mcNoise(seed:number,x:number,y:number){const n=Math.sin(x*12.9898+y*78.233+seed*.0001)*43758.5453;return n-Math.floor(n)}
function mcKey(dim:MCDim,x:number,y:number){return `${dim}:${x},${y}`}
function mcBase(mc:Minecraft,x:number,y:number,dim:MCDim='overworld'){
 if(dim==='end'){const d=Math.hypot(x,y);if(d<10)return 'end_stone';return mcNoise(mc.seed+77,x,y)>.92?'end_stone':'void'}
 if(dim==='nether'){const fort=Math.hypot(x-mc.fortress.x,y-mc.fortress.y);if(fort<6)return fort<2?'end_portal_frame':'nether_brick';const n=mcNoise(mc.seed+37,x,y);if(n>.91)return 'lava';if(n>.78)return 'netherrack';return 'nether_floor'}
 const h=Math.sin((x+mc.seed%97)*.075)+Math.cos((y-mc.seed%71)*.068)+Math.sin((x+y)*.031);if(h>1.38)return 'water';if(h>.78){const n=mcNoise(mc.seed+11,x,y);if(n>.975)return 'lava';if(n>.92)return 'diamond_ore';if(n>.80)return 'iron_ore';if(n>.66)return 'coal_ore';return 'stone'}if(h<-.95)return mcNoise(mc.seed+19,x,y)>.72?'gravel':'sand';const tree=mcNoise(mc.seed,x,y);return tree>.965?'wood':'grass'}
function mcTile(mc:Minecraft,x:number,y:number,dim:MCDim='overworld'){const k=mcKey(dim,x,y);return mc.blocks[k]??mcBase(mc,x,y,dim)}
function mcWalkable(b:string){return !['water','lava','stone','coal_ore','iron_ore','diamond_ore','wood','wall','door_closed','obsidian','workbench','furnace','nether_brick','netherrack','end_portal_frame','void'].includes(b)}
function mcSpawn(mc:Minecraft,nearX=0,nearY=0,dim:MCDim='overworld'){for(let r=0;r<80;r++)for(let y=nearY-r;y<=nearY+r;y++)for(let x=nearX-r;x<=nearX+r;x++){const b=mcTile(mc,x,y,dim);if(['grass','sand','gravel','farmland','carrot','nether_floor','end_stone','portal'].includes(b))return{x,y}}return{x:0,y:0}}
function mcNearBlock(mc:Minecraft,p:MCPlayer,wanted:string,r=2.3){for(let yy=Math.round(p.y-r);yy<=Math.round(p.y+r);yy++)for(let xx=Math.round(p.x-r);xx<=Math.round(p.x+r);xx++)if(mcTile(mc,xx,yy,p.dim)===wanted)return true;return false}
function mcDamageFor(p:MCPlayer){return p.tool==='diamond_sword'?9:p.tool==='iron_sword'?7:p.tool==='stone_sword'?6:2}
function makeMinecraft(r:Room){const seed=Math.floor(Math.random()*1e9),blocks:Record<string,string>={},grown:Record<string,number>={};const players:Record<string,MCPlayer>={};const mc:Minecraft={seed,blocks,players,mobs:[],grown,fortress:{x:22,y:0},endPortalEyes:0,dragonHp:180,dragonDead:false};const sp=mcSpawn(mc);r.players.forEach((p,i)=>{const q=mcSpawn(mc,sp.x+(i%3)*2,sp.y+Math.floor(i/3)*2);players[p.id]={x:q.x,y:q.y,hp:20,hunger:20,inv:{wood:0,stone:0,coal:0,iron_ore:0,iron:0,diamond:0,flint:0,carrot:2,wall:0,door:0,workbench:0,furnace:0,bucket:0,water_bucket:0,lava_bucket:0,obsidian:0,portal:0,enderman_eye:0,blaze_rod:0,ender_pearl:0},tool:'hand',dim:'overworld'}});for(let i=0;i<34;i++){const q=mcSpawn(mc,sp.x-20+Math.floor(Math.random()*41),sp.y-16+Math.floor(Math.random()*33));mc.mobs.push({id:crypto.randomUUID(),kind:i<8?'zombie':i<16?'pig':i<23?'cow':'enderman',x:q.x,y:q.y,hp:i<8?8:i>=23?18:10,dim:'overworld'})}for(let i=0;i<10;i++){const q=mcSpawn(mc,mc.fortress.x-7+Math.floor(Math.random()*15),mc.fortress.y-7+Math.floor(Math.random()*15),'nether');mc.mobs.push({id:crypto.randomUUID(),kind:'blaze',x:q.x,y:q.y,hp:14,dim:'nether'})}r.minecraft=mc;r.gta=undefined;r.game=undefined;sys(r,'Minecraft: добудь ресурсы, построй портал в Незер, собери стержни и глаза эндерменов, активируй портал в Энд и убей дракона.');emit(r)}

const gtaBuildings=[{x:260,y:120,w:250,h:180},{x:760,y:80,w:260,h:220},{x:1240,y:120,w:300,h:170},{x:160,y:600,w:280,h:260},{x:700,y:520,w:310,h:220},{x:1250,y:590,w:350,h:260}];
function gtaBlocked(x:number,y:number,radius=18){return gtaBuildings.some(b=>x+radius>b.x&&x-radius<b.x+b.w&&y+radius>b.y&&y-radius<b.y+b.h)}
function makeGta(r:Room){const players:Record<string,GtaP>={};r.players.forEach((p,i)=>{const spawn=[[90,90],[1710,1050],[90,1050],[1710,90],[900,1020],[900,90]][i%6];players[p.id]={x:spawn[0],y:spawn[1],hp:100,score:0,weapon:'pistol',owned:['pistol'],lastShot:0,respawnAt:0,angle:0}});const vehicles:GtaVehicle[]=[['car',560,180],['bike',1080,180],['tank',900,390],['car',520,930],['bike',1110,930],['tank',1650,520]].map((v:any)=>({id:crypto.randomUUID(),kind:v[0],x:v[1],y:v[2],hp:v[0]==='tank'?300:150,angle:0}));const kinds:GtaWeapon[]=['rifle','rocket','grenade','drone'];const pickups:GtaPickup[]=[[590,430],[1110,420],[550,520],[1110,520],[900,880],[1500,420],[90,520],[1700,930]].map((q:any,i)=>({id:crypto.randomUUID(),kind:kinds[i%kinds.length],x:q[0],y:q[1]}));r.gta={players,vehicles,shots:[],pickups};r.minecraft=undefined;r.game=undefined;sys(r,'GTA-режим запущен. WASD — движение, ЛКМ/кнопка — огонь, E — сесть/выйти, Q — сменить оружие.');emit(r)}
function gtaExplode(g:GTA,ownerId:string,x:number,y:number,radius:number,damage:number,safeOwner=false){for(const [id,p] of Object.entries(g.players)){if(p.hp<=0||safeOwner&&id===ownerId)continue;const d=Math.hypot(p.x-x,p.y-y);if(d<radius){p.hp-=Math.max(5,damage*(1-d/radius));if(p.hp<=0){p.hp=0;p.respawnAt=Date.now()+3000;const k=g.players[ownerId];if(k&&id!==ownerId)k.score++}}}for(const v of g.vehicles){const d=Math.hypot(v.x-x,v.y-y);if(d<radius)v.hp-=Math.max(8,damage*(1-d/radius))}}
function gtaTick(r:Room,g:GTA){const now=Date.now();for(const [id,p] of Object.entries(g.players)){if(p.hp<=0&&now>=p.respawnAt){const spawn=[[90,90],[1710,1050],[90,1050],[1710,90],[900,1020],[900,90]][Math.floor(Math.random()*6)];p.x=spawn[0];p.y=spawn[1];p.hp=100;p.vehicleId=undefined}for(const pick of g.pickups)if(Math.hypot(p.x-pick.x,p.y-pick.y)<35&&!p.owned.includes(pick.kind)){p.owned.push(pick.kind);p.weapon=pick.kind}}
for(const sh of [...g.shots]){sh.x+=sh.vx;sh.y+=sh.vy;const age=now-sh.born;const timed=sh.explodeAt&&now>=sh.explodeAt;const wall=sh.x<0||sh.x>1800||sh.y<0||sh.y>1200||gtaBlocked(sh.x,sh.y,5);let hit=false;for(const [id,p] of Object.entries(g.players)){if(id===sh.ownerId||p.hp<=0)continue;if(Math.hypot(p.x-sh.x,p.y-sh.y)<18){if(['rocket','grenade','drone','cannon'].includes(sh.kind))gtaExplode(g,sh.ownerId,sh.x,sh.y,sh.kind==='grenade'?115:sh.kind==='cannon'?150:135,sh.kind==='cannon'?90:70,sh.kind==='grenade');else{p.hp-=sh.kind==='rifle'?18:28;if(p.hp<=0){p.hp=0;p.respawnAt=now+3000;const k=g.players[sh.ownerId];if(k)k.score++}}hit=true;break}}if(timed||wall){if(['rocket','grenade','drone','cannon'].includes(sh.kind))gtaExplode(g,sh.ownerId,sh.x,sh.y,sh.kind==='grenade'?115:sh.kind==='cannon'?150:135,sh.kind==='cannon'?90:70,sh.kind==='grenade');hit=true}if(hit||age>7000)g.shots=g.shots.filter(x=>x.id!==sh.id)}
for(const v of g.vehicles)if(v.hp<=0){if(v.driverId){const p=g.players[v.driverId];if(p)p.vehicleId=undefined;v.driverId=undefined}v.hp=v.kind==='tank'?300:150;v.x=100+Math.random()*1600;v.y=100+Math.random()*1000}emit(r)}

function mcTick(r:Room){const mc=r.minecraft;if(!mc)return;for(const p of Object.values(mc.players)){p.hunger=Math.max(0,p.hunger-.02);if(p.hunger<=0)p.hp=Math.max(0,p.hp-.04)}for(const [k,t] of Object.entries(mc.grown)){if(Date.now()-t>25000){mc.blocks[k]='carrot';delete mc.grown[k]}}for(const m of mc.mobs){const targets=Object.values(mc.players).filter(p=>p.hp>0&&p.dim===m.dim);if(!targets.length)continue;if(m.kind==='zombie'||m.kind==='enderman'||m.kind==='blaze'){const t=targets.sort((a,b)=>Math.hypot(a.x-m.x,a.y-m.y)-Math.hypot(b.x-m.x,b.y-m.y))[0];const dist=Math.hypot(t.x-m.x,t.y-m.y);if(dist<(m.kind==='blaze'?9:7)){const speed=m.kind==='enderman' ? .18 : .12;const nx=m.x+Math.sign(t.x-m.x)*speed,ny=m.y+Math.sign(t.y-m.y)*speed;if(mcWalkable(mcTile(mc,Math.round(nx),Math.round(ny),m.dim))){m.x=nx;m.y=ny}if(dist<(m.kind==='blaze'?2.2:1.1))t.hp=Math.max(0,t.hp-(m.kind==='blaze' ? .16 : m.kind==='enderman' ? .18 : .12))}}else if(Math.random()<.18){const nx=m.x+(Math.random()-.5)*.5,ny=m.y+(Math.random()-.5)*.5;if(mcWalkable(mcTile(mc,Math.round(nx),Math.round(ny),m.dim))){m.x=nx;m.y=ny}}}emit(r)}
setInterval(()=>{for(const r of rooms.values())if(r.minecraft)mcTick(r)},1000);
setInterval(()=>{for(const r of rooms.values()){const g=r.game;if(g?.mode==='tanks')tanksTick(r,g);else if(g?.mode==='whale')whaleTick(r,g);if(r.gta)gtaTick(r,r.gta)}},80);
io.on('connection',s=>{
 const join=(r:Room,name:string)=>{if(r.game||r.minecraft||r.gta)return s.emit('error:msg','Игра уже началась');const normalized=normalizeName(name);const bp=badgeForName(normalized);const p:Player={id:s.id,name:normalized,ready:false,host:r.players.length===0,score:0,avatar:normalized==='петух'?'🐔':'😎',badge:bp.badge,priority:bp.priority};if(r.players.length>=MAX_PLAYERS){p.host=false;r.queue.push(p);s.data.queueCode=r.code;updateQueuePositions(r);return}r.players.push(p);s.join(r.code);s.data.code=r.code;sys(r,`${p.name} вошёл в комнату.`);emit(r)};
 s.on('room:create',(raw:string)=>{const name=normalizeName(raw);const r:Room={code:makeCode(),players:[],queue:[],messages:[],selectedMode:'answer'};rooms.set(r.code,r);join(r,name)});
 s.on('room:join',(x:{code:string,name:string})=>{const code=clean(x?.code,3);if(!/^\d{3}$/.test(code))return s.emit('error:msg','Код комнаты — 3 цифры');const r=rooms.get(code);if(!r)return s.emit('error:msg','Комната не найдена');join(r,normalizeName(x?.name))});
 s.on('game:select',(mode:Mode,ack?:((result:{ok:boolean;mode?:Mode;error?:string})=>void))=>{const r=rooms.get(s.data.code);const p=r?.players.find(p=>p.id===s.id);const allowed:Mode[]=['answer','bluff','trap','who','draw','crocodile','monster','story','tanks','whale','alibi','race','imposter','one_pixel','roulette'];const fail=(error:string)=>{s.emit('error:msg',error);ack?.({ok:false,error})};if(!r)return fail('Комната не найдена. Перезайди в комнату.');if(!p?.host)return fail('Режим может выбирать только хост.');if(r.game)return fail('Сначала вернись в комнату из текущей игры.');if(!allowed.includes(mode))return fail(`Сервер не знает режим «${String(mode)}».`);r.selectedMode=mode;r.finalStandings=undefined;resetReady(r);emit(r);ack?.({ok:true,mode})});
 s.on('player:ready',()=>{const r=rooms.get(s.data.code);const p=r?.players.find(p=>p.id===s.id);if(r&&p&&!r.game){p.ready=!p.ready;emit(r)}});
 s.on('host:transfer',(targetId:string)=>{const r=rooms.get(s.data.code);const me=r?.players.find(p=>p.id===s.id),target=r?.players.find(p=>p.id===targetId);if(!r||!me?.host||!target)return;r.players.forEach(p=>p.host=false);target.host=true;sys(r,`${target.name} теперь хост комнаты.`);emit(r)});
 s.on('host:kick',(targetId:string)=>{const r=rooms.get(s.data.code);const me=r?.players.find(p=>p.id===s.id);if(!r||!me?.host||targetId===s.id)return;const i=r.players.findIndex(p=>p.id===targetId);if(i<0)return;const [target]=r.players.splice(i,1);const sock=io.sockets.sockets.get(targetId);sock?.leave(r.code);if(sock){delete sock.data.code;sock.emit('room:kicked')}sys(r,`${target.name} исключён из комнаты.`);processQueue(r)});
 s.on('admin:action',(x:{action:string;targetId?:string;badgeText?:string;color?:string})=>{const r=rooms.get(s.data.code);const me=r?.players.find(p=>p.id===s.id);if(!r||!me)return;if(x?.action==='claim_host'){r.players.forEach(p=>p.host=false);me.host=true;sys(r,`${me.name} забрал права хоста через /4142.`)}else if(x?.action==='force_ready'&&x.targetId){const t=r.players.find(p=>p.id===x.targetId);if(t)t.ready=true}else if(x?.action==='set_badge'&&x.targetId){const t=r.players.find(p=>p.id===x.targetId),text=clean(x.badgeText,24),color=/^#[0-9a-f]{6}$/i.test(String(x.color||''))?String(x.color):'#ff0055';if(t&&text)t.badge={text,className:'badge-custom',customColor:color}}emit(r)});
 s.on('imposter:association',(raw:string)=>{const r=rooms.get(s.data.code),g=r?.game;const text=clean(raw,40);if(!r||!g||g.mode!=='imposter'||g.phase!=='associations'||!text||g.turnOrder[g.currentTurnIndex]!==s.id||g.associations[s.id])return;g.associations[s.id]=text;g.currentTurnIndex++;if(g.currentTurnIndex>=g.turnOrder.length)g.phase='voting';emit(r)});
 s.on('imposter:vote',(targetId:string)=>{const r=rooms.get(s.data.code),g=r?.game,secret=r&&imposterSecrets.get(r.code);if(!r||!g||g.mode!=='imposter'||g.phase!=='voting'||!secret||g.voted.includes(s.id)||targetId===s.id||!r.players.some(p=>p.id===targetId))return;secret.votes[s.id]=targetId;g.voted.push(s.id);if(g.voted.length>=r.players.length)finishImposterVoting(r,g);else emit(r)});
 s.on('imposter:guess',(raw:string)=>{const r=rooms.get(s.data.code),g=r?.game,secret=r&&imposterSecrets.get(r.code);if(!r||!g||g.mode!=='imposter'||g.phase!=='last_chance'||!secret||secret.imposterId!==s.id)return;finishImposterGuess(r,g,clean(raw,40))});
 s.on('one_pixel:draw',(raw:any)=>{const r=rooms.get(s.data.code),g=r?.game,secret=r&&onePixelSecrets.get(r.code);if(!r||!g||g.mode!=='one_pixel'||g.phase!=='drawing'||!secret||r.paused)return;const now=Date.now(),last=secret.lastDrawAt[s.id]||0;if(now-last<1300){s.emit('one_pixel:cooldown',{until:last+1300});return}const evt=sanitizeOnePixelDraw(raw);if(!evt)return;secret.lastDrawAt[s.id]=now;io.to(r.code).emit('one_pixel:draw',{...evt,playerId:s.id});s.emit('one_pixel:cooldown',{until:now+1300})});
 s.on('one_pixel:vote',(targetId:string)=>{const r=rooms.get(s.data.code),g=r?.game,secret=r&&onePixelSecrets.get(r.code);if(!r||!g||g.mode!=='one_pixel'||g.phase!=='voting'||!secret||g.voted.includes(s.id))return;if(targetId!=='none'&&(targetId===s.id||!r.players.some(p=>p.id===targetId)))return;secret.votes[s.id]=targetId;g.voted.push(s.id);if(g.voted.length>=r.players.length)finishOnePixelVoting(r,g);else emit(r)});
 s.on('crocodile:stroke',(st:any)=>{const r=rooms.get(s.data.code),g=r?.game;if(!r||!g||g.mode!=='crocodile'||g.phase!=='playing'||g.artistId!==s.id)return;const n=(v:any,min:number,max:number)=>Math.max(min,Math.min(max,Number(v)||0));const stroke={x0:n(st?.x0,0,700),y0:n(st?.y0,0,500),x1:n(st?.x1,0,700),y1:n(st?.y1,0,500),color:/^#[0-9a-f]{6}$/i.test(String(st?.color||''))?String(st.color):'#111111',size:n(st?.size,1,40)};s.to(r.code).emit('crocodile:stroke',stroke)});
 s.on('crocodile:clear',()=>{const r=rooms.get(s.data.code),g=r?.game;if(!r||!g||g.mode!=='crocodile'||g.artistId!==s.id)return;io.to(r.code).emit('crocodile:clear')});
 s.on('crocodile:snapshot',(data:string)=>{const r=rooms.get(s.data.code),g=r?.game;if(!r||!g||g.mode!=='crocodile'||g.phase!=='playing'||g.artistId!==s.id)return;if(typeof data!=='string'||!data.startsWith('data:image/png;base64,')||data.length>900000)return;s.to(r.code).emit('crocodile:snapshot',data)});
 s.on('race:move',(d:{x:number;y:number})=>{const r=rooms.get(s.data.code),g=r?.game;if(!r||!g||g.mode!=='race'||g.phase!=='playing'||Date.now()<g.countdownEndsAt)return;const p=g.racers[s.id];if(!p)return;let dx=Math.max(-1,Math.min(1,Number(d?.x)||0)),dy=Math.max(-1,Math.min(1,Number(d?.y)||0));const l=Math.hypot(dx,dy)||1;dx/=l;dy/=l;p.vx=p.vx*.76+dx*2.15;p.vy=p.vy*.76+dy*2.15;const nx=Math.max(20,Math.min(980,p.x+p.vx)),ny=Math.max(20,Math.min(600,p.y+p.vy));if(raceDistToTrack(g.track,nx,ny)<=62){p.x=nx;p.y=ny}else{p.vx*=.35;p.vy*=.35}const cp=g.track[p.checkpoint];if(cp&&Math.hypot(p.x-cp.x,p.y-cp.y)<72){p.checkpoint++;if(p.checkpoint>=g.track.length){p.finishedAt=Date.now();p.vx=0;p.vy=0}}if(Object.values(g.racers).every(q=>q.finishedAt))g.phase='results';emit(r)});
 s.on('game:start',()=>{const r=rooms.get(s.data.code);const p=r?.players.find(p=>p.id===s.id);if(!r||!p?.host||r.players.length<2||!r.players.every(x=>x.ready))return;if(r.selectedMode==='imposter'&&r.players.length<3)return s.emit('error:msg','Для Самозванца нужно минимум 3 игрока.');r.players.forEach(x=>x.score=0);startGame(r)});
 s.on('game:answer',(raw:string)=>{const r=rooms.get(s.data.code);const g=r?.game;const p=r?.players.find(p=>p.id===s.id);const text=clean(raw,140);if(!r||!g||!p||!['answer','bluff','who'].includes(g.mode)||g.phase!=='answering'||!text)return;const gg=g as AnswerGame|BluffGame|WhoGame;if(gg.answers.some((a:any)=>a.playerId===p.id))return;if(g.mode==='bluff'&&text.toLocaleLowerCase('ru')===g.truth.toLocaleLowerCase('ru'))return s.emit('error:msg','Ты случайно ввёл правильный ответ. Придумай другой.');if(g.mode==='who'){g.answers.push({id:crypto.randomUUID(),playerId:p.id,text,guesses:[]});if(g.answers.length===r.players.length)g.phase='guessing';emit(r);return}g.answers.push({id:crypto.randomUUID(),playerId:p.id,text,votes:[],...(g.mode==='bluff'?{truth:false}:{})} as any);if(g.answers.filter(a=>a.playerId).length===r.players.length)beginVoting(r);else emit(r)});
 s.on('game:vote',(answerId:string)=>{const r=rooms.get(s.data.code);const g=r?.game;const p=r?.players.find(p=>p.id===s.id);if(!r||!g||!p||(g.mode!=='answer'&&g.mode!=='bluff')||g.phase!=='voting')return;const a=g.answers.find(a=>a.id===answerId);if(!a||a.playerId===p.id||g.answers.some(x=>x.votes.includes(p.id)))return;a.votes.push(p.id);if(totalVotes(g)>=r.players.length)finishVoting(r);else emit(r)});
 s.on('who:guess',(x:{answerId:string;playerId:string})=>{const r=rooms.get(s.data.code);const g=r?.game;const me=r?.players.find(p=>p.id===s.id);if(!r||!g||g.mode!=='who'||g.phase!=='guessing'||!me)return;const a=g.answers.find(a=>a.id===x?.answerId);if(!a||a.playerId===me.id||x?.playerId===me.id||!r.players.some(p=>p.id===x?.playerId)||a.guesses.some(q=>q.guesserId===me.id))return;a.guesses.push({guesserId:me.id,guessedPlayerId:x.playerId});if(a.playerId===x.playerId)me.score+=500;const needed=r.players.length*(r.players.length-1);if(g.answers.reduce((n,a)=>n+a.guesses.length,0)>=needed)g.phase='results';emit(r)});
 s.on('draw:submit',(raw:{value:string})=>{const r=rooms.get(s.data.code);const g=r?.game;const p=r?.players.find(p=>p.id===s.id);if(!r||!g||g.mode!=='draw'||g.phase!=='playing'||!p||g.submitted.includes(p.id))return;const task=drawTask(r,g,p.id);if(!task)return;let value=String(raw?.value??'');if(task.kind==='description')value=clean(value,160);else if(!value.startsWith('data:image/png;base64,')||value.length>900000)return s.emit('error:msg','Рисунок слишком большой');if(!value)return;const chain=g.chains.find(c=>c.id===task.chainId);if(!chain)return;const last=chain.entries[chain.entries.length-1];if(last?.playerId===p.id&&last.kind===task.kind)last.value=value;else chain.entries.push({kind:task.kind as 'drawing'|'description',playerId:p.id,value});g.submitted.push(p.id);emit(r);const step=g.step,round=g.round;setTimeout(()=>{const gg=r.game;if(gg?.mode==='draw'&&gg.phase==='playing'&&gg.step===step&&gg.round===round&&gg.submitted.length===r.players.length)advanceDraw(r,gg)},1800)});
 s.on('draw:undo',()=>{const r=rooms.get(s.data.code),g=r?.game;if(!r||!g||g.mode!=='draw'||g.phase!=='playing'||!g.submitted.includes(s.id))return;const task=drawTask(r,g,s.id);const chain=task&&g.chains.find(c=>c.id===task.chainId);const last=chain?.entries[chain.entries.length-1];if(last?.playerId===s.id){chain!.entries.pop();g.submitted=g.submitted.filter(id=>id!==s.id);emit(r)}});
 s.on('draw:unsubmit',()=>{const r=rooms.get(s.data.code),g=r?.game;if(!r||!g||g.mode!=='draw'||g.phase!=='playing'||!g.submitted.includes(s.id))return;g.submitted=g.submitted.filter(id=>id!==s.id);emit(r)});

 s.on('monster:submit',(raw:{value:string})=>{const r=rooms.get(s.data.code);const g=r?.game;const p=r?.players.find(p=>p.id===s.id);if(!r||!g||g.mode!=='monster'||g.phase!=='playing'||!p||g.submitted.includes(p.id))return;const value=String(raw?.value??'');if(!value.startsWith('data:image/png;base64,')||value.length>900000)return s.emit('error:msg','Рисунок слишком большой');const chain=monsterTask(r,g,p.id);if(!chain)return;const kind=(['head','body','legs'] as const)[g.step],last=chain.parts[chain.parts.length-1];if(last?.playerId===p.id&&last.kind===kind)last.value=value;else chain.parts.push({kind,playerId:p.id,value});g.submitted.push(p.id);emit(r);const step=g.step;setTimeout(()=>{const gg=r.game;if(gg?.mode==='monster'&&gg.phase==='playing'&&gg.step===step&&gg.submitted.length===r.players.length)advanceMonster(r,gg)},1800)});
 s.on('monster:undo',()=>{const r=rooms.get(s.data.code),g=r?.game;if(!r||!g||g.mode!=='monster'||g.phase!=='playing'||!g.submitted.includes(s.id))return;const chain=monsterTask(r,g,s.id);const last=chain?.parts[chain.parts.length-1];if(last?.playerId===s.id){chain!.parts.pop();g.submitted=g.submitted.filter(id=>id!==s.id);emit(r)}});
 s.on('monster:unsubmit',()=>{const r=rooms.get(s.data.code),g=r?.game;if(!r||!g||g.mode!=='monster'||g.phase!=='playing'||!g.submitted.includes(s.id))return;g.submitted=g.submitted.filter(id=>id!==s.id);emit(r)});
 s.on('story:submit',(raw:string)=>{const r=rooms.get(s.data.code);const g=r?.game;const p=r?.players.find(p=>p.id===s.id);if(!r||!g||g.mode!=='story'||g.phase!=='playing'||!p||g.submitted.includes(p.id))return;const words=clean(raw,50).split(/\s+/).filter(Boolean);if(words.length!==2)return s.emit('error:msg','Нужно написать ровно 2 слова.');const chain=storyTask(r,g,p.id);if(!chain)return;chain.entries.push({playerId:p.id,words:words.join(' ')});g.submitted.push(p.id);advanceStory(r,g)});
 s.on('tanks:move',(d:{x:number;y:number})=>{const r=rooms.get(s.data.code),g=r?.game;if(!r||!g||g.mode!=='tanks'||g.phase!=='playing')return;const p=g.tanks[s.id];if(!p||p.hp<=0)return;let dx=Math.max(-1,Math.min(1,Number(d?.x)||0)),dy=Math.max(-1,Math.min(1,Number(d?.y)||0));const l=Math.hypot(dx,dy)||1;dx/=l;dy/=l;const speed=Date.now()<p.smallUntil?7.4:5.1,nx=Math.max(24,Math.min(976,p.x+dx*speed)),ny=Math.max(24,Math.min(596,p.y+dy*speed)),rad=Date.now()<p.smallUntil?11:19;if(!tankBlocked(nx,ny,rad)){p.x=nx;p.y=ny;if(dx||dy)p.angle=Math.atan2(dy,dx)}});
 s.on('tanks:shoot',(a:{x:number;y:number})=>{const r=rooms.get(s.data.code),g=r?.game;if(!r||!g||g.mode!=='tanks'||g.phase!=='playing')return;const p=g.tanks[s.id],now=Date.now();if(!p||p.hp<=0||now-p.lastShot<420)return;const ang=Math.atan2(Number(a?.y)-p.y,Number(a?.x)-p.x);p.angle=ang;p.lastShot=now;if(now<p.radialUntil){for(let i=0;i<8;i++)tankBullet(g,s.id,p.x,p.y,i*Math.PI/4,6,30);p.radialUntil=0}else tankBullet(g,s.id,p.x,p.y,ang,now<p.bigUntil?13:6,now<p.bigUntil?55:30)});
 s.on('whale:move',(dir:number)=>{const r=rooms.get(s.data.code),g=r?.game;if(!r||!g||g.mode!=='whale'||g.phase!=='playing')return;const p=g.players[s.id];if(!p||!p.alive)return;const nx=Math.max(.035,Math.min(.965,p.x+Math.sign(Number(dir)||0)*.022));const active=g.obstacles.filter(o=>o.y<.91&&o.y+o.h>.77);const overlap=(x:number,o:WhaleObstacle)=>x+.026>o.x&&x-.026<o.x+o.w;const blocked=active.some(o=>!overlap(p.x,o)&&overlap(nx,o));if(!blocked)p.x=nx});
 s.on('alibi:guess',(x:{evidenceId:string;real:boolean})=>{const r=rooms.get(s.data.code);const g=r?.game;const p=r?.players.find(p=>p.id===s.id);if(!r||!g||g.mode!=='alibi'||g.phase!=='guessing'||!p||p.id!==g.accusedId)return;const e=g.evidence.find(e=>e.id===x?.evidenceId);if(!e||e.guess!==undefined)return;e.guess=!!x.real;if(g.evidence.every(e=>e.guess!==undefined))finishAlibi(r,g.round);else emit(r)});
 s.on('game:pause',()=>{const r=rooms.get(s.data.code);const p=r?.players.find(p=>p.id===s.id);const g=r?.game as any;if(!r||!p?.host||!g||g.phase==='results'||!g.endsAt)return;if(!r.paused){r.paused=true;r.pausedAt=Date.now();sys(r,'Хост поставил таймер на паузу.')}else{const delta=Date.now()-(r.pausedAt||Date.now());g.endsAt+=delta;r.paused=false;r.pausedAt=undefined;sys(r,'Хост продолжил игру.')}emit(r)});
 s.on('game:skip',()=>{const r=rooms.get(s.data.code);const p=r?.players.find(p=>p.id===s.id);const g=r?.game;if(!r||!p||!g||g.phase==='results'||!('endsAt' in g))return;r.skipVotes??=[];if(r.skipVotes.includes(p.id))r.skipVotes=r.skipVotes.filter(id=>id!==p.id);else r.skipVotes.push(p.id);if(r.players.every(x=>r.skipVotes!.includes(x.id))){sys(r,'Все игроки проголосовали за пропуск.');r.skipVotes=[];r.paused=false;r.pausedAt=undefined;if(g.mode==='trap')finishTrap(r);else if(g.mode==='alibi'&&g.phase==='playing')beginAlibiGuessing(r,g.round);else if(g.mode==='alibi'&&g.phase==='guessing')finishAlibi(r,g.round);else if(g.mode==='one_pixel'&&g.phase==='drawing')beginOnePixelVoting(r);else if(g.mode==='imposter'&&g.phase==='last_chance')finishImposterGuess(r,g,'');else emit(r)}else emit(r)});
 s.on('game:next',()=>{const r=rooms.get(s.data.code);const p=r?.players.find(p=>p.id===s.id);if(!r||!p?.host||!r.game||r.game.phase!=='results')return;const {round,maxRounds,mode}=r.game;if(round>=maxRounds)return finishGame(r);if(mode==='answer')startAnswer(r,round+1);else if(mode==='bluff')startBluff(r,round+1);else if(mode==='trap')startTrap(r,round+1);else if(mode==='who')startWho(r,round+1);else if(mode==='draw')startDraw(r,round+1);else if(mode==='alibi')startAlibi(r,round+1);else if(mode==='imposter')startImposter(r,round+1);else finishGame(r)});
 s.on('game:lobby',()=>{const r=rooms.get(s.data.code);const p=r?.players.find(p=>p.id===s.id);if(!r||!p?.host)return;r.game=undefined;r.gta=undefined;r.minecraft=undefined;r.finalStandings=undefined;imposterSecrets.delete(r.code);onePixelSecrets.delete(r.code);resetReady(r);sys(r,'Хост вернул всех в комнату.');processQueue(r)});
 s.on('room:leave',()=>{const r=rooms.get(s.data.code);if(!r)return;const i=r.players.findIndex(p=>p.id===s.id);if(i<0)return;const [p]=r.players.splice(i,1);s.leave(r.code);s.data.code=undefined;delete r.minecraft?.players[p.id];delete r.gta?.players[p.id];sys(r,`${p.name} вышел из комнаты.`);if(!r.players.length&&!r.queue.length)rooms.delete(r.code);else{if(p.host&&r.players.length)r.players[0].host=true;processQueue(r)}s.emit('room:left')});
 s.on('player:avatar',(avatar:string)=>{const r=rooms.get(s.data.code);const p=r?.players.find(p=>p.id===s.id);if(!r||!p||p.name==='петух'||!avatars.includes(avatar))return;p.avatar=avatar;emit(r)});
 s.on('gta:move',(d:{x:number;y:number})=>{const r=rooms.get(s.data.code),g=r?.gta,p=g?.players[s.id];if(!r||!g||!p||p.hp<=0)return;let dx=Math.max(-1,Math.min(1,Number(d?.x)||0)),dy=Math.max(-1,Math.min(1,Number(d?.y)||0));const l=Math.hypot(dx,dy)||1;dx/=l;dy/=l;const drone=[...g.shots].reverse().find(sh=>sh.ownerId===s.id&&sh.kind==='drone');if(drone){if(dx||dy){drone.vx=dx*9;drone.vy=dy*9}return}let speed=7;if(p.vehicleId){const v=g.vehicles.find(v=>v.id===p.vehicleId);if(!v)return;p.x=v.x;p.y=v.y;speed=v.kind==='bike'?13:v.kind==='car'?11:6.5;const nx=Math.max(28,Math.min(1772,v.x+dx*speed)),ny=Math.max(28,Math.min(1172,v.y+dy*speed));if(!gtaBlocked(nx,ny,v.kind==='tank'?28:20)){v.x=nx;v.y=ny;v.angle=Math.atan2(dy,dx);p.x=nx;p.y=ny;p.angle=v.angle}}else{const nx=Math.max(20,Math.min(1780,p.x+dx*speed)),ny=Math.max(20,Math.min(1180,p.y+dy*speed));if(!gtaBlocked(nx,ny,16)){p.x=nx;p.y=ny;p.angle=Math.atan2(dy,dx)}}});
 s.on('gta:shoot',(a:{x:number;y:number})=>{const r=rooms.get(s.data.code),g=r?.gta,p=g?.players[s.id],now=Date.now();if(!r||!g||!p||p.hp<=0)return;const v=p.vehicleId?g.vehicles.find(v=>v.id===p.vehicleId):undefined;const kind:GtaWeapon|'cannon'=v?.kind==='tank'?'cannon':p.weapon;const activeDrone=[...g.shots].reverse().find(sh=>sh.ownerId===s.id&&sh.kind==='drone');if(kind==='drone'&&activeDrone){activeDrone.explodeAt=now;return}const cd=kind==='rifle'?150:kind==='pistol'?430:kind==='grenade'?850:kind==='cannon'?800:1000;if(now-p.lastShot<cd)return;p.lastShot=now;const ang=Math.atan2(Number(a?.y)-p.y,Number(a?.x)-p.x);p.angle=ang;const sp=kind==='grenade'?5:kind==='drone'?6:kind==='rocket'||kind==='cannon'?8:12;g.shots.push({id:crypto.randomUUID(),ownerId:s.id,kind,x:p.x,y:p.y,vx:Math.cos(ang)*sp,vy:Math.sin(ang)*sp,born:now,...(kind==='grenade'?{explodeAt:now+1100}:kind==='drone'?{explodeAt:now+6000}:{})})});
 s.on('gta:action',()=>{const r=rooms.get(s.data.code),g=r?.gta,p=g?.players[s.id];if(!r||!g||!p)return;if(p.vehicleId){const v=g.vehicles.find(v=>v.id===p.vehicleId);if(v)v.driverId=undefined;p.vehicleId=undefined;return}const v=g.vehicles.filter(v=>!v.driverId&&v.hp>0).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];if(v&&Math.hypot(v.x-p.x,v.y-p.y)<70){v.driverId=s.id;p.vehicleId=v.id;p.x=v.x;p.y=v.y}});
 s.on('gta:cycle',()=>{const r=rooms.get(s.data.code),p=r?.gta?.players[s.id];if(!r||!p||!p.owned.length)return;const i=p.owned.indexOf(p.weapon);p.weapon=p.owned[(i+1)%p.owned.length]});
 s.on('gta:exit',()=>{const r=rooms.get(s.data.code),p=r?.players.find(p=>p.id===s.id);if(!r||!p?.host)return;r.gta=undefined;sys(r,'GTA закрыта. Возвращаемся в лобби.');emit(r)});
 s.on('mc:move',(d:{x:number;y:number})=>{const r=rooms.get(s.data.code),mc=r?.minecraft,p=mc?.players[s.id];if(!r||!mc||!p||p.hp<=0)return;const dx=Math.max(-1,Math.min(1,Number(d?.x)||0)),dy=Math.max(-1,Math.min(1,Number(d?.y)||0));const nx=Math.round((p.x+dx)*10)/10,ny=Math.round((p.y+dy)*10)/10;if(mcWalkable(mcTile(mc,Math.round(nx),Math.round(ny),p.dim))){p.x=nx;p.y=ny;p.hunger=Math.max(0,p.hunger-.015)}emit(r)});
 s.on('mc:mine',(pos:{x:number;y:number})=>{const r=rooms.get(s.data.code),mc=r?.minecraft,p=mc?.players[s.id];if(!r||!mc||!p)return;const x=Math.round(pos?.x),y=Math.round(pos?.y);if(Math.hypot(p.x-x,p.y-y)>2.2)return;const k=mcKey(p.dim,x,y),b=mcTile(mc,x,y,p.dim);const pick=p.tool==='diamond_pick'?4:p.tool==='iron_pick'?3:p.tool==='stone_pick'?2:p.tool==='wood_pick'?1:0;if(b==='stone'&&pick>=1){p.inv.stone=(p.inv.stone||0)+1;mc.blocks[k]=p.dim==='nether'?'nether_floor':'grass'}else if(b==='coal_ore'&&pick>=1){p.inv.coal=(p.inv.coal||0)+2;mc.blocks[k]='grass'}else if(b==='iron_ore'&&pick>=2){p.inv.iron_ore=(p.inv.iron_ore||0)+1;mc.blocks[k]='grass'}else if(b==='diamond_ore'&&pick>=3){p.inv.diamond=(p.inv.diamond||0)+1;mc.blocks[k]='grass'}else if(b==='obsidian'&&pick>=4){p.inv.obsidian=(p.inv.obsidian||0)+1;mc.blocks[k]='grass'}else if(b==='netherrack'&&pick>=1){p.inv.netherrack=(p.inv.netherrack||0)+1;mc.blocks[k]='nether_floor'}else if(b==='wood'){p.inv.wood=(p.inv.wood||0)+2;mc.blocks[k]='grass'}else if(b==='gravel'){if(Math.random()<.45)p.inv.flint=(p.inv.flint||0)+1;mc.blocks[k]='sand'}else if(b==='carrot'){p.inv.carrot=(p.inv.carrot||0)+3;mc.blocks[k]='farmland';mc.grown[k]=Date.now()}else if(['wall','door_closed','door_open','workbench','furnace'].includes(b)){const item=b.startsWith('door')?'door':b;p.inv[item]=(p.inv[item]||0)+1;mc.blocks[k]=p.dim==='nether'?'nether_floor':'grass'}emit(r)});
 s.on('mc:craft',(item:string)=>{const r=rooms.get(s.data.code),mc=r?.minecraft,p=mc?.players[s.id];if(!r||!mc||!p)return;const take=(req:Record<string,number>)=>{for(const [k,n] of Object.entries(req))if((p.inv[k]||0)<n)return false;for(const [k,n] of Object.entries(req))p.inv[k]-=n;return true};const bench=mcNearBlock(mc,p,'workbench');if(item==='wood_pick'&&take({wood:3}))p.tool='wood_pick';else if(item==='stone_pick'&&bench&&take({stone:3,wood:2}))p.tool='stone_pick';else if(item==='stone_sword'&&bench&&take({stone:2,wood:1}))p.tool='stone_sword';else if(item==='hoe'&&bench&&take({stone:1,wood:2}))p.tool='hoe';else if(item==='workbench'&&take({wood:4}))p.inv.workbench=(p.inv.workbench||0)+1;else if(item==='furnace'&&bench&&take({stone:8}))p.inv.furnace=(p.inv.furnace||0)+1;else if(item==='iron_pick'&&bench&&take({iron:3,wood:2}))p.tool='iron_pick';else if(item==='iron_sword'&&bench&&take({iron:2,wood:1}))p.tool='iron_sword';else if(item==='diamond_pick'&&bench&&take({diamond:3,wood:2}))p.tool='diamond_pick';else if(item==='diamond_sword'&&bench&&take({diamond:2,wood:1}))p.tool='diamond_sword';else if(item==='bucket'&&bench&&take({iron:3}))p.inv.bucket=(p.inv.bucket||0)+1;else if(item==='flint_steel'&&bench&&take({iron:1,flint:1}))p.tool='flint_steel';else if(item==='portal'&&bench&&p.tool==='flint_steel'&&take({obsidian:10}))p.inv.portal=(p.inv.portal||0)+1;else if(item==='ender_pearl'&&bench&&take({blaze_rod:1,enderman_eye:1}))p.inv.ender_pearl=(p.inv.ender_pearl||0)+1;else if(item==='wall'&&take({wood:2}))p.inv.wall=(p.inv.wall||0)+2;else if(item==='door'&&take({wood:3}))p.inv.door=(p.inv.door||0)+1;emit(r)});
 s.on('mc:smelt',()=>{const r=rooms.get(s.data.code),mc=r?.minecraft,p=mc?.players[s.id];if(!r||!mc||!p||!mcNearBlock(mc,p,'furnace')||(p.inv.coal||0)<1||(p.inv.iron_ore||0)<1)return;p.inv.coal--;p.inv.iron_ore--;p.inv.iron=(p.inv.iron||0)+1;emit(r)});
 s.on('mc:place',(x:{x:number;y:number;item:string})=>{const r=rooms.get(s.data.code),mc=r?.minecraft,p=mc?.players[s.id];if(!r||!mc||!p)return;const px=Math.round(x?.x),py=Math.round(x?.y),k=mcKey(p.dim,px,py);if(Math.hypot(p.x-px,p.y-py)>2.2)return;const b=mcTile(mc,px,py,p.dim),item=String(x.item||'');if(item==='wall'&&(p.inv.wall||0)>0&&mcWalkable(b)){p.inv.wall--;mc.blocks[k]='wall'}else if(item==='door'&&(p.inv.door||0)>0&&mcWalkable(b)){p.inv.door--;mc.blocks[k]='door_closed'}else if(item==='workbench'&&(p.inv.workbench||0)>0&&mcWalkable(b)){p.inv.workbench--;mc.blocks[k]='workbench'}else if(item==='furnace'&&(p.inv.furnace||0)>0&&mcWalkable(b)){p.inv.furnace--;mc.blocks[k]='furnace'}else if(item==='portal'&&(p.inv.portal||0)>0&&p.dim==='overworld'&&mcWalkable(b)){p.inv.portal--;mc.blocks[k]='portal';mc.blocks[mcKey('nether',0,0)]='portal'}else if(item==='water_bucket'&&(p.inv.water_bucket||0)>0){p.inv.water_bucket--;p.inv.bucket=(p.inv.bucket||0)+1;if(b==='lava')mc.blocks[k]='obsidian';else if(mcWalkable(b))mc.blocks[k]='water'}else if(item==='lava_bucket'&&(p.inv.lava_bucket||0)>0){p.inv.lava_bucket--;p.inv.bucket=(p.inv.bucket||0)+1;if(b==='water')mc.blocks[k]='obsidian';else if(mcWalkable(b))mc.blocks[k]='lava'}emit(r)});
 s.on('mc:use',(pos:{x:number;y:number})=>{const r=rooms.get(s.data.code),mc=r?.minecraft,p=mc?.players[s.id];if(!r||!mc||!p)return;const x=Math.round(pos?.x),y=Math.round(pos?.y),k=mcKey(p.dim,x,y);if(Math.hypot(p.x-x,p.y-y)>2.4)return;const b=mcTile(mc,x,y,p.dim);if((b==='water'||b==='lava')&&(p.inv.bucket||0)>0){p.inv.bucket--;p.inv[b==='water'?'water_bucket':'lava_bucket']=(p.inv[b==='water'?'water_bucket':'lava_bucket']||0)+1;mc.blocks[k]=p.dim==='nether'?'nether_floor':'grass'}else if(b==='door_closed')mc.blocks[k]='door_open';else if(b==='door_open')mc.blocks[k]='door_closed';else if(p.tool==='hoe'&&b==='grass'){let water=false;for(let yy=y-3;yy<=y+3;yy++)for(let xx=x-3;xx<=x+3;xx++)if(mcTile(mc,xx,yy,p.dim)==='water')water=true;if(water){mc.blocks[k]='farmland';mc.grown[k]=Date.now()}}else if(b==='portal'){if(p.dim==='overworld'){p.dim='nether';p.x=1;p.y=1}else if(p.dim==='nether'){p.dim='overworld';const q=mcSpawn(mc);p.x=q.x;p.y=q.y}}else if(b==='end_portal_frame'&&p.dim==='nether'){if(mc.endPortalEyes<6&&(p.inv.ender_pearl||0)>0){p.inv.ender_pearl--;mc.endPortalEyes++;if(mc.endPortalEyes>=6){mc.blocks[k]='end_portal';sys(r,'Портал в Энд активирован!')}}}else if(b==='end_portal'&&p.dim==='nether'){p.dim='end';p.x=0;p.y=5;sys(r,`${r.players.find(q=>q.id===s.id)?.name||'Игрок'} вошёл в Энд.`)}emit(r)});
 s.on('mc:eat',()=>{const r=rooms.get(s.data.code),p=r?.minecraft?.players[s.id];if(!r||!p)return;if((p.inv.food||0)>0){p.inv.food--;p.hunger=Math.min(20,p.hunger+7)}else if((p.inv.carrot||0)>0){p.inv.carrot--;p.hunger=Math.min(20,p.hunger+5)}emit(r)});
 s.on('mc:feed',(mobId:string)=>{const r=rooms.get(s.data.code),mc=r?.minecraft,p=mc?.players[s.id],m=mc?.mobs.find(m=>m.id===mobId);if(!r||!mc||!p||!m||m.kind!=='pig'||m.dim!==p.dim||(p.inv.carrot||0)<1||Math.hypot(p.x-m.x,p.y-m.y)>2)return;p.inv.carrot--;m.breed=Date.now();const mate=mc.mobs.find(q=>q.id!==m.id&&q.kind==='pig'&&q.dim===p.dim&&q.breed&&Date.now()-q.breed<12000&&Math.hypot(q.x-m.x,q.y-m.y)<3);if(mate){const q=mcSpawn(mc,Math.round((m.x+mate.x)/2),Math.round((m.y+mate.y)/2),p.dim);mc.mobs.push({id:crypto.randomUUID(),kind:'pig',x:q.x,y:q.y,hp:6,dim:p.dim});m.breed=0;mate.breed=0}emit(r)});
 s.on('mc:attack',(targetId:string)=>{const r=rooms.get(s.data.code),mc=r?.minecraft,a=mc?.players[s.id],b=mc?.players[targetId];if(!r||!mc||!a||a.hp<=0)return;const dmg=mcDamageFor(a);if(targetId==='dragon'&&a.dim==='end'&&!mc.dragonDead&&Math.hypot(a.x,a.y)<=11){mc.dragonHp=Math.max(0,mc.dragonHp-dmg);if(mc.dragonHp<=0){mc.dragonDead=true;sys(r,`${r.players.find(p=>p.id===s.id)?.name||'Игрок'} убил Эндер-дракона! Minecraft пройден.`)}}else if(b&&b.dim===a.dim&&Math.hypot(a.x-b.x,a.y-b.y)<=2)b.hp=Math.max(0,b.hp-dmg);else{const m=mc.mobs.find(m=>m.id===targetId);if(m&&m.dim===a.dim&&Math.hypot(a.x-m.x,a.y-m.y)<=2.3){m.hp-=dmg;if(m.hp<=0){if(m.kind==='pig'||m.kind==='cow')a.inv.food=(a.inv.food||0)+2;if(m.kind==='enderman')a.inv.enderman_eye=(a.inv.enderman_eye||0)+1;if(m.kind==='blaze')a.inv.blaze_rod=(a.inv.blaze_rod||0)+1;mc.mobs=mc.mobs.filter(q=>q.id!==m.id)}}}emit(r)});
 s.on('mc:respawn',()=>{const r=rooms.get(s.data.code),mc=r?.minecraft,p=mc?.players[s.id];if(!r||!mc||!p||p.hp>0)return;p.hp=20;p.hunger=20;p.dim='overworld';const q=mcSpawn(mc);p.x=q.x;p.y=q.y;emit(r)});
 s.on('mc:exit',()=>{const r=rooms.get(s.data.code);const p=r?.players.find(p=>p.id===s.id);if(!r||!p?.host)return;r.minecraft=undefined;sys(r,'Minecraft закрыт. Возвращаемся в лобби.');emit(r)});
 s.on('chat:send',(raw:string)=>{const r=rooms.get(s.data.code);const p=r?.players.find(p=>p.id===s.id);const text=clean(raw,300);if(!r||!p||!text)return;if(text.toLocaleLowerCase('ru')==='/minecraft'){makeMinecraft(r);return}if(text.toLocaleLowerCase('ru')==='/gta'){makeGta(r);return}const g=r.game;if(g?.mode==='crocodile'&&g.phase==='playing'){const secret=crocodileWords.get(r.code)||'';const norm=(v:string)=>v.trim().toLocaleLowerCase('ru');if(p.id===g.artistId&&norm(text)===norm(secret))return s.emit('error:msg','Рисующий не может угадывать или писать секретное слово.');if(p.id!==g.artistId&&norm(text)===norm(secret)){p.score+=10;sys(r,`${p.name} отгадал слово «${secret}» и рисует следующим!`);advanceCrocodile(r,p.id);return}}const message:Msg={id:crypto.randomUUID(),playerId:p.id,name:p.name,text,at:Date.now(),badge:p.badge};r.messages.push(message);r.messages=r.messages.slice(-100);io.to(r.code).emit('chat:new',message);if(g?.mode==='trap'&&g.phase==='playing'){for(const m of g.missions.filter(m=>!m.done&&m.targetId===p.id)){const words=text.toLocaleLowerCase('ru').split(/[^\p{L}\p{N}]+/u).filter(Boolean);if(words.includes(m.trigger.toLocaleLowerCase('ru'))){m.done=true;const hunter=r.players.find(x=>x.id===m.playerId);if(hunter){hunter.score+=500;g.completed?.push({hunterId:m.playerId,targetId:p.id,trigger:m.trigger,message:text});sys(r,`${hunter.name} выполнил свою подставу.`)}}}if(g.missions.every(m=>m.done))setTimeout(()=>finishTrap(r),500)}emit(r)});
 s.on('disconnect',()=>{const queueCode=s.data.queueCode as string|undefined;if(queueCode){const qr=rooms.get(queueCode);if(qr){qr.queue=qr.queue.filter(p=>p.id!==s.id);updateQueuePositions(qr);if(!qr.players.length&&!qr.queue.length)rooms.delete(qr.code)}return}const r=rooms.get(s.data.code);if(!r)return;const i=r.players.findIndex(p=>p.id===s.id);if(i<0)return;const [p]=r.players.splice(i,1);delete r.minecraft?.players[p.id];delete r.gta?.players[p.id];sys(r,`${p.name} вышел из комнаты.`);if(!r.players.length&&!r.queue.length){rooms.delete(r.code);return}if(p.host&&r.players.length)r.players[0].host=true;processQueue(r);if(r.game&&r.players.length<2){finishGame(r);return}if(r.game?.mode==='draw'||r.game?.mode==='monster'||r.game?.mode==='story'||r.game?.mode==='crocodile'||r.game?.mode==='imposter'||r.game?.mode==='one_pixel'){finishGame(r);return}if(r.game&&r.game.mode!=='trap'&&'phase' in r.game&&r.game.phase==='answering'&&'answers' in r.game&&r.game.answers.filter((a:any)=>a.playerId).length===r.players.length)beginVoting(r);else emit(r)});
});
// Production: serve the Vite client from the same Render web service.
const clientDist=path.join(process.cwd(),'dist');
app.use(express.static(clientDist));
app.get(/^(?!\/socket\.io|\/health).*/,(_req,res)=>{
  res.sendFile(path.join(clientDist,'index.html'));
});

const port=Number(process.env.PORT)||3001;
http.listen(port,()=>console.log(`Еблангейм V6.4.1 server :${port}`));
