import express from 'express';
import { createServer } from 'http';
import { Server } from 'socket.io';
import cors from 'cors';
import crypto from 'crypto';
import path from 'path';

type Mode='answer'|'bluff'|'trap'|'who'|'draw'|'monster'|'story'|'tanks'|'whale'|'alibi'|'roulette';
type Prefix={text:string;color?:string;priority:number};type Player={id:string;name:string;ready:boolean;host:boolean;score:number;avatar:string;prefix?:Prefix};
type Msg={id:string;playerId?:string;name:string;text:string;system?:boolean;at:number};
type Answer={id:string;playerId:string;text:string;votes:string[]};
type AnswerGame={mode:'answer';phase:'answering'|'voting'|'results';round:number;maxRounds:number;prompt:string;answers:Answer[]};
type Bluff={id:string;playerId?:string;text:string;votes:string[];truth:boolean};
type BluffGame={mode:'bluff';phase:'answering'|'voting'|'results';round:number;maxRounds:number;question:string;truth:string;answers:Bluff[]};
type Mission={playerId:string;targetId:string;trigger:string;done:boolean};
type TrapGame={mode:'trap';phase:'playing'|'results';round:number;maxRounds:number;endsAt:number;missions:Mission[];completed?:{hunterId:string;targetId:string;trigger:string;message:string}[]};
type WhoGuess={guesserId:string;guessedPlayerId:string};
type WhoAnswer={id:string;playerId:string;text:string;guesses:WhoGuess[]};
type WhoGame={mode:'who';phase:'answering'|'guessing'|'results';round:number;maxRounds:number;prompt:string;answers:WhoAnswer[]};
type DrawEntry={kind:'prompt'|'drawing'|'description';playerId?:string;value:string};
type DrawChain={id:string;entries:DrawEntry[]};
type DrawGame={mode:'draw';phase:'playing'|'results';round:number;maxRounds:number;step:number;maxSteps:number;submitted:string[];chains:DrawChain[]};
type MonsterPart={kind:'head'|'body'|'legs';playerId:string;value:string};
type MonsterChain={id:string;parts:MonsterPart[]};
type MonsterGame={mode:'monster';phase:'playing'|'results';round:number;maxRounds:number;step:number;submitted:string[];chains:MonsterChain[]};
type StoryEntry={playerId:string;words:string};
type StoryChain={id:string;entries:StoryEntry[]};
type StoryGame={mode:'story';phase:'playing'|'results';round:number;maxRounds:number;step:number;maxSteps:number;submitted:string[];chains:StoryChain[]};
type TankP={x:number;y:number;hp:number;score:number;angle:number;lastShot:number;respawnAt:number;bigUntil:number;smallUntil:number;radialUntil:number};
type TankBullet={id:string;ownerId:string;x:number;y:number;vx:number;vy:number;r:number;damage:number;born:number};
type TankDrop={id:string;x:number;y:number;kind:'big'|'small'|'radial'};
type TanksGame={mode:'tanks';phase:'playing'|'results';round:number;maxRounds:number;endsAt:number;tanks:Record<string,TankP>;bullets:TankBullet[];drops:TankDrop[];nextDropAt:number};
type WhaleP={x:number;alive:boolean;score:number;gap:number};
type WhaleObstacle={id:string;x:number;y:number;w:number;h:number};
type WhaleGame={mode:'whale';phase:'playing'|'results';round:number;maxRounds:number;endsAt:number;startedAt:number;players:Record<string,WhaleP>;obstacles:WhaleObstacle[];nextSpawnAt:number};
type AlibiEvidence={id:string;ownerId:string;text:string;real:boolean;guess?:boolean};
type AlibiGame={mode:'alibi';phase:'playing'|'guessing'|'results';round:number;maxRounds:number;accusedId:string;charge:string;alibi:string[];evidence:AlibiEvidence[];endsAt:number};
type Game=AnswerGame|BluffGame|TrapGame|WhoGame|DrawGame|MonsterGame|StoryGame|TanksGame|WhaleGame|AlibiGame;
type MCPlayer={x:number;y:number;hp:number;hunger:number;inv:Record<string,number>;tool:'hand'|'wood_pick'|'stone_sword'|'hoe'}; type MCMob={id:string;kind:'zombie'|'pig'|'cow';x:number;y:number;hp:number;breed?:number}; type Minecraft={seed:number;blocks:Record<string,string>;players:Record<string,MCPlayer>;mobs:MCMob[];grown:Record<string,number>};
type GtaWeapon='pistol'|'rifle'|'rocket'|'grenade'|'drone';
type GtaP={x:number;y:number;hp:number;score:number;weapon:GtaWeapon;owned:GtaWeapon[];vehicleId?:string;lastShot:number;respawnAt:number;angle:number};
type GtaVehicle={id:string;kind:'car'|'bike'|'tank';x:number;y:number;hp:number;driverId?:string;angle:number};
type GtaShot={id:string;ownerId:string;kind:GtaWeapon|'cannon';x:number;y:number;vx:number;vy:number;born:number;explodeAt?:number};
type GtaPickup={id:string;kind:GtaWeapon;x:number;y:number};
type GTA={players:Record<string,GtaP>;vehicles:GtaVehicle[];shots:GtaShot[];pickups:GtaPickup[]};
type Room={code:string;players:Player[];messages:Msg[];selectedMode:Mode;adminIds?:string[];notifications?:{id:string;text:string;kind:string;at:number}[];game?:Game;lastMode?:Exclude<Mode,'roulette'>;finalStandings?:Player[];paused?:boolean;pausedAt?:number;skipVotes?:string[];minecraft?:Minecraft;gta?:GTA;whoPromptHistory?:string[]};

const app=express();app.use(cors());app.use(express.json());
const http=createServer(app);const io=new Server(http,{cors:{origin:'*'},maxHttpBufferSize:2_000_000});const rooms=new Map<string,Room>();
app.get('/health',(_req,res)=>res.json({ok:true,rooms:rooms.size}));
function clean(v:any,max:number){return String(v??'').trim().slice(0,max)}
function makeCode(){for(let i=0;i<900;i++){const code=String(100+Math.floor(Math.random()*900));if(!rooms.has(code))return code}throw new Error('Нет свободных кодов комнат')}
function emit(r:Room){io.to(r.code).emit('room:state',r)}
function prefixFor(name:string):Prefix|undefined{const n=name.toLocaleLowerCase('ru');if(['blagin','благин'].includes(n))return {text:'БОСС',priority:100,color:'#ffcc00'};if(n==='саша'||n==='саня'||n==='александр')return {text:'СПОНСОР 12₽',priority:80,color:'#00e5ff'};if(n==='филатов')return {text:'СПОНСОР 10₽',priority:60,color:'#ff66cc'};return undefined}
function notify(r:Room,text:string,kind='info'){r.notifications??=[];r.notifications.push({id:crypto.randomUUID(),text,kind,at:Date.now()});r.notifications=r.notifications.slice(-10);io.to(r.code).emit('notification',r.notifications[r.notifications.length-1])}

function sys(r:Room,text:string){r.messages.push({id:crypto.randomUUID(),name:'Система',text,system:true,at:Date.now()});r.messages=r.messages.slice(-100)}
function resetReady(r:Room){r.players.forEach(p=>p.ready=false)}
function resetRoundControls(r:Room){r.skipVotes=[];r.paused=false;r.pausedAt=undefined}
function timedRemaining(r:Room){const g=r.game as any;return g?.endsAt?Math.max(0,g.endsAt-Date.now()):0}
function scheduleCheck(r:Room,kind:'trap'|'alibi-play'|'alibi-guess',round:number){setTimeout(()=>{const g=r.game as any;if(!g||g.round!==round)return;if(r.paused)return scheduleCheck(r,kind,round);const left=timedRemaining(r);if(left>0)return setTimeout(()=>scheduleCheck(r,kind,round),Math.min(left+20,500));if(kind==='trap'&&g.mode==='trap'&&g.phase==='playing')finishTrap(r);if(kind==='alibi-play'&&g.mode==='alibi'&&g.phase==='playing')beginAlibiGuessing(r,round);if(kind==='alibi-guess'&&g.mode==='alibi'&&g.phase==='guessing')finishAlibi(r,round)},250)}

const answerPrompts=['Худшая фраза, которую можно услышать от хирурга перед наркозом: ______','Самая бесполезная функция нового телефона: ______','Настоящая причина, почему преподаватель задержался на пару: ______','Что никогда не стоит писать в резюме: ______','Самое подозрительное объявление на Avito: ______','Что точно не должен говорить пилот перед взлётом: ______'];
const bluffQuestions=[{q:'Как называется боязнь длинных слов?',a:'Гиппопотомонстросескиппедалофобия'},{q:'Какой продукт археологи находили в древнеегипетских гробницах всё ещё пригодным в пищу?',a:'Мёд'},{q:'Какое животное имеет отпечатки пальцев, очень похожие на человеческие?',a:'Коала'},{q:'Как называется точка на поверхности Земли, противоположная другой точке?',a:'Антипод'},{q:'Какой металл при комнатной температуре остаётся жидким?',a:'Ртуть'},{q:'Как называется символ &?',a:'Амперсанд'}];
const trapWords=['да','нет','зачем','ладно','окей','что','почему','когда','где','можно'];
const whoPeople=['директор школы','охранник супермаркета','учитель физкультуры','сосед сверху','таксист','продавец шаурмы','врач','полицейский','ведущий новостей','стример','курьер','повар','президент','космонавт','пилот','машинист метро','сантехник','программист','диджей','футболист','библиотекарь','парикмахер','кассир','строитель','фокусник','фотограф','тренер','геймер','блогер','рыбак','фермер','робот','инопланетянин','пират','рыцарь','детектив','учёный','миллиардер','дворник','директор цирка'];
const whoPlaces=['в школе','на вокзале','в метро','в магазине','в больнице','в лесу','на крыше','в лифте','на свадьбе','на экзамене','в аэропорту','в автобусе','в компьютерном клубе','в банке','на пляже','на Луне','в зоопарке','на стройке','в библиотеке','в столовой','в спортзале','в музее','на концерте','на футбольном матче','в полиции','в парикмахерской','в отеле','в торговом центре','в гараже','на заправке','в аквапарке','в цирке','в кинотеатре','на необитаемом острове','в подвале','в космосе','на уроке','на собеседовании','в очереди к врачу','на родительском собрании'];
const whoObjects=['трактор','холодильник','доширак','арбуз','ноутбук','огнетушитель','самокат','микроволновку','диван','принтер','кактус','палатку','бензопилу','ванну','манекен','телевизор','мешок картошки','генератор','велосипед','шкаф','аквариум','пылесос','барабан','лестницу','тележку','матрас','роутер','чайник','шлем','резиновую утку','пиццу','сейф','лопату','гирю','клавиатуру','костюм банана','корону','дорожный знак','газонокосилку','картонную коробку'];
const whoConditions=['если тебе дадут миллион рублей','если пропадёт интернет','если начнётся зомби-апокалипсис','если тебя назначат директором','если ты проснёшься невидимым','если отменят все правила','если останешься один в городе','если тебе нельзя будет врать','если ты попадёшь в прошлое','если ты попадёшь в будущее','если за тобой будет гнаться гусь','если у тебя останется 100 рублей','если тебя покажут по телевизору','если ты станешь знаменитым','если все телефоны исчезнут','если ты выиграешь спор','если тебя запрут в школе ночью','если тебе дадут суперсилу','если ты сможешь читать мысли','если ты станешь котом на день','если весь день нельзя будет говорить','если придётся жить в магазине неделю','если ты найдёшь чемодан денег','если тебя позовут в космос','если ты станешь учителем','если твой будильник заговорит','если все вокруг уснут','если начнётся эвакуация','если ты случайно станешь мэром','если тебе разрешат украсть одну вещь','если можно будет отменить один закон','если ты застрянешь в лифте','если тебя перепутают со знаменитостью','если тебе дадут танк','если ты найдёшь портал','если исчезнет электричество','если тебя вызовут к директору','если появится клон тебя','если твой питомец начнёт говорить','если завтра конец света'];
const whoTemplates=[
 (i:number)=>`Что ты первым делом сделаешь, ${whoConditions[i]}?`,
 (i:number)=>`Какую самую тупую причину можно придумать, чтобы ${whoPeople[i]} оказался ${whoPlaces[(i+7)%40]}?`,
 (i:number)=>`Что бы ты точно не хотел услышать от человека, который работает как ${whoPeople[i]}?`,
 (i:number)=>`Зачем нормальному человеку может срочно понадобиться ${whoObjects[i]} ${whoPlaces[(i+13)%40]}?`,
 (i:number)=>`Как бы ты объяснил родителям, почему у тебя дома внезапно появился ${whoObjects[i]}?`,
 (i:number)=>`Какое правило ты бы ввёл ${whoPlaces[i]}, если бы мог делать что угодно?`,
 (i:number)=>`Что самое подозрительное мог бы сказать ${whoPeople[i]} ${whoPlaces[(i+19)%40]}?`,
 (i:number)=>`Какой самый нелепый план спасения ты придумаешь, ${whoConditions[(i+5)%40]}?`
];
function generateWhoPrompt(r:Room){r.whoPromptHistory??=[];for(let tries=0;tries<80;tries++){const i=Math.floor(Math.random()*40),t=Math.floor(Math.random()*whoTemplates.length),q=whoTemplates[t](i);if(!r.whoPromptHistory.includes(q)){r.whoPromptHistory.push(q);r.whoPromptHistory=r.whoPromptHistory.slice(-80);return q}}return whoTemplates[Math.floor(Math.random()*whoTemplates.length)](Math.floor(Math.random()*40))}
const drawPrompts=[
 'Кот пытается списать контрольную','Гусь работает охранником в магазине','Преподаватель едет на паре верхом на принтере','Шаурма сбегает от покупателя','Два голубя делят последний доширак','Человек объясняет банкомату, что денег нет','Хомяк проходит собеседование на работу','Скелет опоздал на автобус',
 'Пингвин чинит компьютер феном','Бабушка участвует в гонках на офисном кресле','Голубь требует вернуть ему долг','Крокодил сдаёт экзамен по информатике','Директор прячется в коробке из-под принтера','Кот проводит родительское собрание','Рыцарь заказывает шаурму через терминал','Инопланетянин пытается пройти школьную вахту','Гусь угоняет автобус','Сантехник сражается с Wi-Fi роутером','Хомяк управляет огромным экскаватором','Скелет делает селфи на паспорт','Капибара работает системным администратором','Пират пишет контрольную по Excel','Голубь выступает на деловой конференции','Кот продаёт подозрительный ноутбук на рынке','Бабушка играет в киберспортивном турнире','Динозавр ждёт маршрутку под дождём','Робот жарит пельмени утюгом','Преподаватель пытается поймать сбежавшую клавиатуру','Пингвин несёт холодильник на девятый этаж','Клоун ремонтирует сервер молотком','Гусь проходит паспортный контроль','Кот открывает шаурмичную на Луне','Человек спорит с кофейным автоматом','Капибара сдаёт зачёт вместо студента','Рыцарь пытается подключиться к школьному Wi-Fi','Инопланетянин покупает доширак ночью','Бабушка взламывает банкомат ложкой','Скелет работает курьером','Голубь защищает диплом','Пингвин устраивается водителем автобуса','Кот пытается спрятать трактор','Хомяк проводит урок физкультуры','Директор школы застрял в автомате с едой','Робот просит списать домашнее задание','Крокодил играет свадьбу в компьютерном клубе','Пират ищет клад в кабинете информатики','Капибара убегает от контролёра','Гусь торгуется за видеокарту','Скелет пытается открыть дверь отпечатком пальца','Кот вызывает такси для холодильника','Бабушка чинит спутник на крыше школы','Голубь работает судьёй на футбольном матче','Пингвин крадётся по библиотеке с бензопилой','Рыцарь защищает последний доширак','Хомяк руководит строительством небоскрёба','Динозавр сидит за первой партой','Инопланетянин фотографируется на студенческий','Капибара объясняет полиции, откуда у неё трактор'
];

// Конструктор тем для Фоторобота. Все элементы уже записаны в форме,
// в которой их можно безопасно склеить без сложного склонения слов.
const drawSubjects=[
 'Кот','Гусь','Голубь','Хомяк','Капибара','Пингвин','Крокодил','Динозавр','Скелет','Робот',
 'Инопланетянин','Пират','Рыцарь','Клоун','Бабушка','Дед','Преподаватель','Директор школы','Студент','Охранник',
 'Курьер','Сантехник','Программист','Таксист','Повар','Полицейский','Космонавт','Археолог','Фокусник','Вампир',
 'Зомби','Снеговик','Ниндзя','Ковбой','Шпион','Викинг','Гном','Волшебник','Медведь','Енот',
 'Жираф','Акула на ножках','Краб','Лягушка','Петух','Собака','Коза','Черепаха','Офисный менеджер','Человек в костюме банана'
];
const drawActions=[
 'чинит','крадёт','прячет','покупает','продаёт','тащит','рисует','фотографирует','ремонтирует','ломает',
 'запускает','догоняет','спасает','выгуливает','допрашивает','обнимает','кормит','будит','моет','готовит',
 'закапывает','распаковывает','собирает','охраняет','ищет','ловит','учит','вызывает','арендует','выбрасывает',
 'заряжает','взвешивает','красит','подписывает','прячет от полиции','пытается продать','пытается съесть','пытается починить','пытается украсть','пытается приручить',
 'несёт на голове','катается верхом на','устраивает драку с','играет в шахматы с','ведёт переговоры с','снимает видео про','заказывает доставку для','строит дом для','проводит собеседование с','объясняет математику для'
];
const drawObjects=[
 'принтер','холодильник','трактор','роутер','школьный компьютер','огромный доширак','шаурму','банкомат','офисное кресло','клавиатуру',
 'мышку','проектор','микроволновку','автобус','самокат','телевизор','пылесос','чайник','унитаз','арбуз',
 'гигантский носок','чемодан денег','мешок картошки','резиновую утку','дорожный знак','спутник','ракету','аквариум','кактус','торговый автомат',
 'огромную ложку','бочку компота','серверную стойку','дверь от машины','палатку','скелет динозавра','коробку пельменей','золотой батон','робота-пылесоса','пачку контрольных',
 'гусеницу экскаватора','мешок клавиатур','игровой автомат','памятник голубю','подводную лодку','надувной бассейн','барабан','генератор','мешок цемента','тележку из супермаркета'
];
const drawCircumstances=[
 'во время контрольной','посреди урока','на крыше школы','в компьютерном клубе','в переполненном автобусе','на свадьбе','на похоронах','в супермаркете','на футбольном поле','в библиотеке',
 'в лифте','на Луне','на необитаемом острове','в кабинете директора','под проливным дождём','в три часа ночи','во время экзамена','на сцене перед толпой','на парковке','в школьной столовой',
 'на вокзале','в аэропорту','в метро','на пляже','в лесу','в пустыне','на Северном полюсе','в космосе','в средневековом замке','в аквапарке',
 'на родительском собрании','во время прямого эфира','на деловой встрече','на уроке физкультуры','в очереди к врачу','на выпускном','во время эвакуации','на секретной военной базе','на дне океана','в зоопарке',
 'на стройке','в музее','в цирке','в отделении полиции','в банке','на заправке','в парикмахерской','на экзамене по вождению','в огромной пробке','на школьной линейке'
];
const drawModifiers=[
 'с закрытыми глазами','одной рукой','стоя на одной ноге','пока все вокруг спят','пока за ним гонится охрана','делая вид, что всё нормально','в костюме банана','в полной темноте','под громкую музыку','с очень серьёзным лицом',
 'не выпуская из рук телефон','с кастрюлей на голове','верхом на офисном кресле','используя только ложку','без обуви','в огромных солнцезащитных очках','под наблюдением полиции','пока рядом снимают репортаж','с инструкцией вверх ногами','вместе с тремя голубями',
 'потому что проиграл спор','потому что так написано в инструкции','потому что опаздывает','потому что ему заплатили 100 рублей','потому что другого плана нет','потому что интернет отключили','потому что дверь заперта','потому что это часть экзамена','потому что за ним следят','потому что он уверен, что так и надо',
 'на глазах у директора','под аплодисменты толпы','с секундомером в зубах','в резиновых сапогах','с плакатом «Я всё контролирую»','не переставая танцевать','пытаясь не разбудить кота','во время видеозвонка','с фонариком вместо микрофона','в сопровождении оркестра',
 'с завязанными глазами','сидя в детской коляске','в противогазе','под звуки пожарной сигнализации','с огромным рюкзаком','притворяясь сотрудником магазина','пока вокруг летают бумажки','с короной на голове','в окружении десяти уток','как будто от этого зависит судьба мира'
];
function randomOf<T>(xs:T[]){return xs[Math.floor(Math.random()*xs.length)]}
function generateDrawPrompt(){return `${randomOf(drawSubjects)} ${randomOf(drawActions)} ${randomOf(drawObjects)} ${randomOf(drawCircumstances)} ${randomOf(drawModifiers)}`}
function makeDrawPrompts(count:number){const out:string[]=[];const seen=new Set<string>();while(out.length<count){const useManual=Math.random()<0.28;const prompt=useManual?randomOf(drawPrompts):generateDrawPrompt();if(!seen.has(prompt)){seen.add(prompt);out.push(prompt)}}return out}

const alibiCases=[
 {charge:'украл все мышки из кабинета информатики',alibi:['В 19:30 ты зашёл в магазин.','Ты был там один.','Купил арбуз и воду.','Вышел в 20:05.'],real:['Чек из магазина пробит в 19:47.','Камера магазина сняла тебя без компании.','На банковской карте есть покупка воды в 19:48.'],fake:['Магазин закрылся ещё в 18:00.','Камера школы сняла тебя в кабинете в 19:40.','Продавец утверждает, что ты покупал отвёртку.']},
 {charge:'продал школьный проектор на Avito',alibi:['С 17:00 до 18:00 ты был в компьютерном клубе.','Ты пришёл туда с Димой.','Платил наличными.','Домой ушёл пешком.'],real:['Администратор клуба помнит тебя около 17:20.','Дима подтвердил, что пришёл вместе с тобой.','Камера у клуба сняла тебя в 17:54.'],fake:['На твоей карте есть оплата такси в 17:15.','Дима заявил, что весь день тебя не видел.','Покупатель проектора назвал твоё имя.']},
 {charge:'съел чужой доширак и подделал алиби',alibi:['Во время пропажи ты сидел в библиотеке.','С собой у тебя был только чай.','Ты ушёл оттуда в 14:10.','До библиотеки ты пришёл на автобусе.'],real:['Библиотекарь видел тебя за столом.','Проездной отмечен в автобусе в 12:58.','Камера выхода показывает тебя в 14:09.'],fake:['В мусорке нашли упаковку с твоими отпечатками.','Библиотека в тот день была закрыта.','Камера столовой сняла тебя с дошираком.']},
 {charge:'ночью переставил все клавиши на школьных клавиатурах',alibi:['В 23:00 ты уже был дома.','Ты играл за компьютером.','С тобой в Discord сидел друг.','Из дома после 22:30 ты не выходил.'],real:['Друг подтвердил звонок в Discord в 23:12.','Домашний роутер зафиксировал твой компьютер онлайн.','Камера подъезда не показывает твоего выхода после 22:30.'],fake:['Твой пропуск использовали в школе в 23:18.','Таксист узнал тебя по фотографии.','На одной клавиатуре нашли твою записку.']}
];
const realModes:Exclude<Mode,'roulette'>[]=['answer','bluff','trap','who','draw','monster','story','tanks','whale','alibi'];
function chooseRoulette(r:Room){const pool=realModes.filter(x=>x!==r.lastMode);return pool[Math.floor(Math.random()*pool.length)]||'answer'}
function modeName(m:Exclude<Mode,'roulette'>){return m==='answer'?'Ответь как еблан':m==='bluff'?'Хуй знает':m==='trap'?'Подстава':m==='who'?'Кто это написал?':m==='draw'?'Фоторобот':m==='monster'?'Сын пробирки':m==='story'?'Продолжи историю':m==='tanks'?'Танчики':m==='whale'?'Беги от кита':'Алиби'}
function startGame(r:Room){resetReady(r);r.finalStandings=undefined;const chosen=r.selectedMode==='roulette'?chooseRoulette(r):r.selectedMode;r.lastMode=chosen;if(r.selectedMode==='roulette')sys(r,`Рулетка выбрала режим: ${modeName(chosen)}.`);if(chosen==='answer')startAnswer(r,1);else if(chosen==='bluff')startBluff(r,1);else if(chosen==='trap')startTrap(r,1);else if(chosen==='who')startWho(r,1);else if(chosen==='draw')startDraw(r,1);else if(chosen==='monster')startMonster(r);else if(chosen==='story')startStory(r);else if(chosen==='tanks')startTanks(r);else if(chosen==='whale')startWhale(r);else startAlibi(r,1)}
function startAnswer(r:Room,round:number){resetRoundControls(r);r.game={mode:'answer',phase:'answering',round,maxRounds:3,prompt:answerPrompts[(round-1)%answerPrompts.length],answers:[]};sys(r,`Раунд ${round} начался.`);emit(r)}
function startBluff(r:Room,round:number){resetRoundControls(r);const x=bluffQuestions[(round-1)%bluffQuestions.length];r.game={mode:'bluff',phase:'answering',round,maxRounds:3,question:x.q,truth:x.a,answers:[]};sys(r,`Раунд ${round} начался.`);emit(r)}
function startWho(r:Room,round:number){resetRoundControls(r);r.game={mode:'who',phase:'answering',round,maxRounds:3,prompt:generateWhoPrompt(r),answers:[]};sys(r,`Кто это написал?: раунд ${round}.`);emit(r)}
function startDraw(r:Room,round:number){resetRoundControls(r);const prompts=makeDrawPrompts(r.players.length);const chains:DrawChain[]=r.players.map((p,i)=>({id:crypto.randomUUID(),entries:[{kind:'prompt' as const,value:prompts[i]}]}));r.game={mode:'draw',phase:'playing',round,maxRounds:2,step:0,maxSteps:Math.max(3,Math.min(5,r.players.length)),submitted:[],chains};sys(r,`Фоторобот: раунд ${round}.`);emit(r)}
function drawTask(r:Room,g:DrawGame,playerId:string){const idx=r.players.findIndex(p=>p.id===playerId);if(idx<0)return null;const chain=g.chains[(idx-g.step%r.players.length+r.players.length)%r.players.length];const last=chain.entries[chain.entries.length-1];return{chainId:chain.id,kind:g.step%2===0?'drawing':'description',source:last}}
function advanceDraw(r:Room,g:DrawGame){if(g.submitted.length<r.players.length)return;g.submitted=[];g.step++;if(g.step>=g.maxSteps){g.phase='results';emit(r);return}emit(r)}
function startMonster(r:Room){resetRoundControls(r);r.game={mode:'monster',phase:'playing',round:1,maxRounds:1,step:0,submitted:[],chains:r.players.map(()=>({id:crypto.randomUUID(),parts:[]}))};sys(r,'Сын пробирки: сначала головы, затем чужие тела, затем чужие ноги.');emit(r)}
function monsterTask(r:Room,g:MonsterGame,playerId:string){const idx=r.players.findIndex(p=>p.id===playerId);if(idx<0)return null;const chain=g.chains[(idx-g.step%r.players.length+r.players.length)%r.players.length];return chain}
function advanceMonster(r:Room,g:MonsterGame){if(g.submitted.length<r.players.length)return;g.submitted=[];g.step++;if(g.step>=3)g.phase='results';emit(r)}
function startStory(r:Room){resetRoundControls(r);r.game={mode:'story',phase:'playing',round:1,maxRounds:1,step:0,maxSteps:6,submitted:[],chains:r.players.map(()=>({id:crypto.randomUUID(),entries:[]}))};sys(r,'Продолжи историю: каждый пишет ровно два слова, потом цепочка переходит другому игроку.');emit(r)}
function storyTask(r:Room,g:StoryGame,playerId:string){const idx=r.players.findIndex(p=>p.id===playerId);if(idx<0)return null;return g.chains[(idx-g.step%r.players.length+r.players.length)%r.players.length]}
function advanceStory(r:Room,g:StoryGame){if(g.submitted.length<r.players.length)return;g.submitted=[];g.step++;if(g.step>=g.maxSteps)g.phase='results';emit(r)}
const tankWalls=[{x:250,y:150,w:130,h:28},{x:620,y:140,w:28,h:160},{x:430,y:360,w:160,h:28},{x:120,y:390,w:110,h:28},{x:760,y:400,w:110,h:28}];
function tankBlocked(x:number,y:number,radius=18){return tankWalls.some(w=>x+radius>w.x&&x-radius<w.x+w.w&&y+radius>w.y&&y-radius<w.y+w.h)}
function startTanks(r:Room){resetRoundControls(r);const tanks:Record<string,TankP>={};r.players.forEach((p,i)=>{const spots=[[90,90],[910,530],[910,90],[90,530],[500,80],[500,540]];const q=spots[i%spots.length];tanks[p.id]={x:q[0],y:q[1],hp:100,score:0,angle:0,lastShot:0,respawnAt:0,bigUntil:0,smallUntil:0,radialUntil:0}});r.game={mode:'tanks',phase:'playing',round:1,maxRounds:1,endsAt:Date.now()+90000,tanks,bullets:[],drops:[],nextDropAt:Date.now()+5000};sys(r,'Танчики: 90 секунд. WASD — движение, ПКМ — выстрел. Аирдропы дают усиление на 10 секунд.');emit(r)}
function tankBullet(g:TanksGame,ownerId:string,x:number,y:number,ang:number,radius:number,damage:number){g.bullets.push({id:crypto.randomUUID(),ownerId,x,y,vx:Math.cos(ang)*10,vy:Math.sin(ang)*10,r:radius,damage,born:Date.now()})}
function tanksTick(r:Room,g:TanksGame){if(g.phase!=='playing')return;const now=Date.now();if(now>=g.endsAt){for(const [id,t] of Object.entries(g.tanks)){const p=r.players.find(p=>p.id===id);if(p)p.score=t.score}g.phase='results';emit(r);return}if(now>=g.nextDropAt&&g.drops.length<4){g.drops.push({id:crypto.randomUUID(),x:70+Math.random()*860,y:70+Math.random()*460,kind:randomOf(['big','small','radial'] as const)});g.nextDropAt=now+7000+Math.random()*5000}for(const [id,t] of Object.entries(g.tanks)){if(t.hp<=0&&now>=t.respawnAt){const q=[[90,90],[910,530],[910,90],[90,530],[500,80],[500,540]][Math.floor(Math.random()*6)];t.x=q[0];t.y=q[1];t.hp=100}for(const d of [...g.drops])if(Math.hypot(t.x-d.x,t.y-d.y)<30){if(d.kind==='big')t.bigUntil=now+10000;if(d.kind==='small')t.smallUntil=now+10000;if(d.kind==='radial')t.radialUntil=now+10000;g.drops=g.drops.filter(x=>x.id!==d.id)}}for(const b of [...g.bullets]){b.x+=b.vx;b.y+=b.vy;if(now-b.born>4000||b.x<0||b.x>1000||b.y<0||b.y>620||tankBlocked(b.x,b.y,b.r)){g.bullets=g.bullets.filter(x=>x.id!==b.id);continue}for(const [id,t] of Object.entries(g.tanks)){if(id===b.ownerId||t.hp<=0)continue;const rr=(now<t.smallUntil?11:19)+b.r;if(Math.hypot(t.x-b.x,t.y-b.y)<rr){t.hp-=b.damage;g.bullets=g.bullets.filter(x=>x.id!==b.id);if(t.hp<=0){t.hp=0;t.respawnAt=now+3000;const killer=g.tanks[b.ownerId];if(killer)killer.score++}break}}}emit(r)}
function startWhale(r:Room){resetRoundControls(r);const players:Record<string,WhaleP>={};r.players.forEach((p,i)=>players[p.id]={x:.25+(i%4)*.16,alive:true,score:0,gap:.44});r.game={mode:'whale',phase:'playing',round:1,maxRounds:1,endsAt:Date.now()+90000,startedAt:Date.now(),players,obstacles:[],nextSpawnAt:Date.now()+850};sys(r,'Погоня от кита: только влево/вправо. Препятствия несутся от горизонта; если застрял — выбирайся в сторону, пока кит не догнал.');emit(r)}
function whaleTick(r:Room,g:WhaleGame){if(g.phase!=='playing')return;const now=Date.now(),elapsed=(now-g.startedAt)/1000,diff=1+elapsed/24,speed=.0105*diff;if(now>=g.nextSpawnAt){const w=.055+Math.random()*.095;g.obstacles.push({id:crypto.randomUUID(),x:.08+Math.random()*(.84-w),y:.03,w,h:.045+Math.random()*.035});g.nextSpawnAt=now+Math.max(220,820/diff)}for(const o of g.obstacles)o.y+=speed;g.obstacles=g.obstacles.filter(o=>o.y<1.08);for(const p of Object.values(g.players)){if(!p.alive)continue;p.score=Math.floor(elapsed*12);const hit=g.obstacles.some(o=>o.y<.91&&o.y+o.h>.77&&p.x+.026>o.x&&p.x-.026<o.x+o.w);p.gap-=.00034*diff;if(hit)p.gap-=.0052*diff;else p.gap=Math.min(.46,p.gap+.00062);if(p.gap<=.035)p.alive=false}if(now>=g.endsAt||Object.values(g.players).every(p=>!p.alive)){for(const [id,q] of Object.entries(g.players)){const p=r.players.find(p=>p.id===id);if(p)p.score=q.score}g.phase='results'}emit(r)}

function startTrap(r:Room,round:number){resetRoundControls(r);const shuffled=[...trapWords].sort(()=>Math.random()-.5);const missions=r.players.map((p,i)=>{const targets=r.players.filter(x=>x.id!==p.id);const target=targets[Math.floor(Math.random()*targets.length)];return{playerId:p.id,targetId:target.id,trigger:shuffled[i%shuffled.length],done:false}});r.game={mode:'trap',phase:'playing',round,maxRounds:3,endsAt:Date.now()+60000,missions,completed:[]};sys(r,`Подстава: раунд ${round}. У вас 60 секунд.`);emit(r);scheduleCheck(r,'trap',round)}
function finishTrap(r:Room){const g=r.game;if(!g||g.mode!=='trap'||g.phase!=='playing')return;g.phase='results';emit(r)}

function startAlibi(r:Room,round:number){resetRoundControls(r);const accused=r.players[(round-1)%r.players.length];const c=alibiCases[(round-1)%alibiCases.length];const investigators=r.players.filter(p=>p.id!==accused.id);const pool=[...c.real.map(text=>({text,real:true})),...c.fake.map(text=>({text,real:false}))].sort(()=>Math.random()-.5);const evidence=investigators.map((p,i)=>({id:crypto.randomUUID(),ownerId:p.id,...pool[i%pool.length]}));r.game={mode:'alibi',phase:'playing',round,maxRounds:Math.min(3,r.players.length),accusedId:accused.id,charge:c.charge,alibi:c.alibi,evidence,endsAt:Date.now()+45000};sys(r,`Алиби: ${accused.name} под подозрением. Следователи получили улики.`);emit(r);scheduleCheck(r,'alibi-play',round)}
function beginAlibiGuessing(r:Room,round:number){const g=r.game;if(!g||g.mode!=='alibi'||g.round!==round||g.phase!=='playing')return;g.phase='guessing';r.skipVotes=[];g.endsAt=Date.now()+30000;sys(r,'Допрос окончен. Подозреваемый должен определить, какие улики настоящие.');emit(r);scheduleCheck(r,'alibi-guess',round)}
function finishAlibi(r:Room,round:number){const g=r.game;if(!g||g.mode!=='alibi'||g.round!==round||g.phase==='results')return;const accused=r.players.find(p=>p.id===g.accusedId);for(const e of g.evidence){const owner=r.players.find(p=>p.id===e.ownerId);if(e.guess===e.real){if(accused)accused.score+=300}else if(e.guess!==undefined&&owner)owner.score+=400}g.phase='results';emit(r)}

function beginVoting(r:Room){const g=r.game;if(!g||g.phase!=='answering'||g.mode==='who')return;if(g.mode==='bluff')g.answers.push({id:crypto.randomUUID(),text:g.truth,votes:[],truth:true});g.phase='voting';emit(r)}
function finishVoting(r:Room){const g=r.game;if(!g||(g.mode!=='answer'&&g.mode!=='bluff')||g.phase!=='voting')return;if(g.mode==='answer'){for(const a of g.answers){const owner=r.players.find(p=>p.id===a.playerId);if(owner)owner.score+=a.votes.length*100}}else{for(const a of g.answers){if(a.truth){for(const voter of a.votes){const p=r.players.find(x=>x.id===voter);if(p)p.score+=1000}}else if(a.playerId){const owner=r.players.find(p=>p.id===a.playerId);if(owner)owner.score+=a.votes.length*500}}}g.phase='results';emit(r)}
function totalVotes(g:AnswerGame|BluffGame){return g.answers.reduce((n,a)=>n+a.votes.length,0)}
function finishGame(r:Room){r.finalStandings=[...r.players].sort((a,b)=>b.score-a.score).map(p=>({...p}));r.game=undefined;resetReady(r);sys(r,'Игра закончена.');emit(r)}

function normalizeName(raw:any){const n=clean(raw,20)||'Игрок';return n.toLocaleLowerCase('ru')==='ефим'?'петух':n}
const avatars=['😎','🤡','🐸','🐱','🐶','🦆','🐧','🦝','🗿','👽','🤖','💀','🧙','🥸','🐔'];
function mcNoise(seed:number,x:number,y:number){const n=Math.sin(x*12.9898+y*78.233+seed*.0001)*43758.5453;return n-Math.floor(n)}
function mcBase(mc:Minecraft,x:number,y:number){const h=Math.sin((x+mc.seed%97)*.075)+Math.cos((y-mc.seed%71)*.068)+Math.sin((x+y)*.031);if(h>1.28)return 'water';if(h>.68)return 'stone';if(h<-.95)return 'sand';const tree=mcNoise(mc.seed,x,y);return tree>.965?'wood':'grass'}
function mcTile(mc:Minecraft,x:number,y:number){const k=`${x},${y}`;return mc.blocks[k]??mcBase(mc,x,y)}
function mcWalkable(b:string){return !['water','stone','wood','wall','door_closed'].includes(b)}
function mcSpawn(mc:Minecraft,nearX=0,nearY=0){for(let r=0;r<80;r++)for(let y=nearY-r;y<=nearY+r;y++)for(let x=nearX-r;x<=nearX+r;x++){const b=mcTile(mc,x,y);if(['grass','sand','farmland','carrot'].includes(b))return{x,y}}return{x:0,y:0}}
function makeMinecraft(r:Room){const seed=Math.floor(Math.random()*1e9),blocks:Record<string,string>={},grown:Record<string,number>={};const players:Record<string,MCPlayer>={};const mc:Minecraft={seed,blocks,players,mobs:[],grown};const sp=mcSpawn(mc);r.players.forEach((p,i)=>{const q=mcSpawn(mc,sp.x+(i%3)*2,sp.y+Math.floor(i/3)*2);players[p.id]={x:q.x,y:q.y,hp:20,hunger:20,inv:{wood:0,stone:0,carrot:2,wall:0,door:0},tool:'hand'}});for(let i=0;i<24;i++){const q=mcSpawn(mc,sp.x-18+Math.floor(Math.random()*37),sp.y-14+Math.floor(Math.random()*29));mc.mobs.push({id:crypto.randomUUID(),kind:i<8?'zombie':i<16?'pig':'cow',x:q.x,y:q.y,hp:i<8?8:10})}r.minecraft=mc;r.gta=undefined;r.game=undefined;sys(r,'Секретный режим активирован: Minecraft.');emit(r)}

const gtaBuildings=[{x:260,y:120,w:250,h:180},{x:760,y:80,w:260,h:220},{x:1240,y:120,w:300,h:170},{x:160,y:600,w:280,h:260},{x:700,y:520,w:310,h:220},{x:1250,y:590,w:350,h:260}];
function gtaBlocked(x:number,y:number,radius=18){return gtaBuildings.some(b=>x+radius>b.x&&x-radius<b.x+b.w&&y+radius>b.y&&y-radius<b.y+b.h)}
function makeGta(r:Room){const players:Record<string,GtaP>={};r.players.forEach((p,i)=>{const spawn=[[90,90],[1710,1050],[90,1050],[1710,90],[900,1020],[900,90]][i%6];players[p.id]={x:spawn[0],y:spawn[1],hp:100,score:0,weapon:'pistol',owned:['pistol'],lastShot:0,respawnAt:0,angle:0}});const vehicles:GtaVehicle[]=[['car',560,180],['bike',1080,180],['tank',900,390],['car',520,930],['bike',1110,930],['tank',1650,520]].map((v:any)=>({id:crypto.randomUUID(),kind:v[0],x:v[1],y:v[2],hp:v[0]==='tank'?300:150,angle:0}));const kinds:GtaWeapon[]=['rifle','rocket','grenade','drone'];const pickups:GtaPickup[]=[[590,430],[1110,420],[550,520],[1110,520],[900,880],[1500,420],[90,520],[1700,930]].map((q:any,i)=>({id:crypto.randomUUID(),kind:kinds[i%kinds.length],x:q[0],y:q[1]}));r.gta={players,vehicles,shots:[],pickups};r.minecraft=undefined;r.game=undefined;sys(r,'GTA-режим запущен. WASD — движение, ЛКМ/кнопка — огонь, E — сесть/выйти, Q — сменить оружие.');emit(r)}
function gtaExplode(g:GTA,ownerId:string,x:number,y:number,radius:number,damage:number,safeOwner=false){for(const [id,p] of Object.entries(g.players)){if(p.hp<=0||safeOwner&&id===ownerId)continue;const d=Math.hypot(p.x-x,p.y-y);if(d<radius){p.hp-=Math.max(5,damage*(1-d/radius));if(p.hp<=0){p.hp=0;p.respawnAt=Date.now()+3000;const k=g.players[ownerId];if(k&&id!==ownerId)k.score++}}}for(const v of g.vehicles){const d=Math.hypot(v.x-x,v.y-y);if(d<radius)v.hp-=Math.max(8,damage*(1-d/radius))}}
function gtaTick(r:Room,g:GTA){const now=Date.now();for(const [id,p] of Object.entries(g.players)){if(p.hp<=0&&now>=p.respawnAt){const spawn=[[90,90],[1710,1050],[90,1050],[1710,90],[900,1020],[900,90]][Math.floor(Math.random()*6)];p.x=spawn[0];p.y=spawn[1];p.hp=100;p.vehicleId=undefined}for(const pick of g.pickups)if(Math.hypot(p.x-pick.x,p.y-pick.y)<35&&!p.owned.includes(pick.kind)){p.owned.push(pick.kind);p.weapon=pick.kind}}
for(const sh of [...g.shots]){sh.x+=sh.vx;sh.y+=sh.vy;const age=now-sh.born;const timed=sh.explodeAt&&now>=sh.explodeAt;const wall=sh.x<0||sh.x>1800||sh.y<0||sh.y>1200||gtaBlocked(sh.x,sh.y,5);let hit=false;for(const [id,p] of Object.entries(g.players)){if(id===sh.ownerId||p.hp<=0)continue;if(Math.hypot(p.x-sh.x,p.y-sh.y)<18){if(['rocket','grenade','drone','cannon'].includes(sh.kind))gtaExplode(g,sh.ownerId,sh.x,sh.y,sh.kind==='grenade'?115:sh.kind==='cannon'?150:135,sh.kind==='cannon'?90:70,sh.kind==='grenade');else{p.hp-=sh.kind==='rifle'?18:28;if(p.hp<=0){p.hp=0;p.respawnAt=now+3000;const k=g.players[sh.ownerId];if(k)k.score++}}hit=true;break}}if(timed||wall){if(['rocket','grenade','drone','cannon'].includes(sh.kind))gtaExplode(g,sh.ownerId,sh.x,sh.y,sh.kind==='grenade'?115:sh.kind==='cannon'?150:135,sh.kind==='cannon'?90:70,sh.kind==='grenade');hit=true}if(hit||age>7000)g.shots=g.shots.filter(x=>x.id!==sh.id)}
for(const v of g.vehicles)if(v.hp<=0){if(v.driverId){const p=g.players[v.driverId];if(p)p.vehicleId=undefined;v.driverId=undefined}v.hp=v.kind==='tank'?300:150;v.x=100+Math.random()*1600;v.y=100+Math.random()*1000}emit(r)}

function mcTick(r:Room){const mc=r.minecraft;if(!mc)return;for(const p of Object.values(mc.players)){p.hunger=Math.max(0,p.hunger-.02);if(p.hunger<=0)p.hp=Math.max(0,p.hp-.04)}for(const [k,t] of Object.entries(mc.grown)){if(Date.now()-t>25000){mc.blocks[k]='carrot';delete mc.grown[k]}}for(const m of mc.mobs){if(m.kind==='zombie'){const targets=Object.values(mc.players).filter(p=>p.hp>0);if(!targets.length)continue;const t=targets.sort((a,b)=>Math.hypot(a.x-m.x,a.y-m.y)-Math.hypot(b.x-m.x,b.y-m.y))[0];if(Math.hypot(t.x-m.x,t.y-m.y)<7){const nx=m.x+Math.sign(t.x-m.x)*.12,ny=m.y+Math.sign(t.y-m.y)*.12;if(mcWalkable(mcTile(mc,Math.round(nx),Math.round(ny)))){m.x=nx;m.y=ny}if(Math.hypot(t.x-m.x,t.y-m.y)<1)t.hp=Math.max(0,t.hp-.12)}}else if(Math.random()<.18){const nx=m.x+(Math.random()-.5)*.5,ny=m.y+(Math.random()-.5)*.5;if(mcWalkable(mcTile(mc,Math.round(nx),Math.round(ny)))){m.x=nx;m.y=ny}}}emit(r)}
setInterval(()=>{for(const r of rooms.values())if(r.minecraft)mcTick(r)},1000);
setInterval(()=>{for(const r of rooms.values()){const g=r.game;if(g?.mode==='tanks')tanksTick(r,g);else if(g?.mode==='whale')whaleTick(r,g);if(r.gta)gtaTick(r,r.gta)}},80);
io.on('connection',s=>{
 const join=(r:Room,name:string)=>{if(r.game||r.minecraft||r.gta)return s.emit('error:msg','Игра уже началась');if(r.players.length>=6)return s.emit('error:msg','В комнате уже 6 человек');const p={id:s.id,name:normalizeName(name),ready:false,host:r.players.length===0,score:0,avatar:normalizeName(name)==='петух'?'🐔':'😎'};r.players.push(p);s.join(r.code);s.data.code=r.code;sys(r,`${p.name} вошёл в комнату.`);emit(r)};
 s.on('room:create',(raw:string)=>{const name=normalizeName(raw);const r:Room={code:makeCode(),players:[],messages:[],selectedMode:'answer',notifications:[]};rooms.set(r.code,r);join(r,name)});
 s.on('room:join',(x:{code:string,name:string})=>{const code=clean(x?.code,3);if(!/^\d{3}$/.test(code))return s.emit('error:msg','Код комнаты — 3 цифры');const r=rooms.get(code);if(!r)return s.emit('error:msg','Комната не найдена');if(r.players.length>=10)return s.emit('error:msg','Комната заполнена');join(r,normalizeName(x?.name))});
 s.on('game:select',(mode:Mode)=>{const r=rooms.get(s.data.code);const p=r?.players.find(p=>p.id===s.id);if(!r||!p?.host||r.game||!['answer','bluff','trap','who','draw','monster','story','tanks','whale','alibi','roulette'].includes(mode))return;r.selectedMode=mode;r.finalStandings=undefined;resetReady(r);emit(r)});
 s.on('player:ready',()=>{const r=rooms.get(s.data.code);const p=r?.players.find(p=>p.id===s.id);if(r&&p&&!r.game){p.ready=!p.ready;emit(r)}});
 s.on('game:start',()=>{const r=rooms.get(s.data.code);const p=r?.players.find(p=>p.id===s.id);if(!r||!p?.host||r.players.length<2||!r.players.every(x=>x.ready))return;r.players.forEach(x=>x.score=0);startGame(r)});
 s.on('game:answer',(raw:string)=>{const r=rooms.get(s.data.code);const g=r?.game;const p=r?.players.find(p=>p.id===s.id);const text=clean(raw,140);if(!r||!g||!p||!['answer','bluff','who'].includes(g.mode)||g.phase!=='answering'||!text)return;const gg=g as AnswerGame|BluffGame|WhoGame;if(gg.answers.some((a:any)=>a.playerId===p.id))return;if(g.mode==='bluff'&&text.toLocaleLowerCase('ru')===g.truth.toLocaleLowerCase('ru'))return s.emit('error:msg','Ты случайно ввёл правильный ответ. Придумай другой.');if(g.mode==='who'){g.answers.push({id:crypto.randomUUID(),playerId:p.id,text,guesses:[]});if(g.answers.length===r.players.length)g.phase='guessing';emit(r);return}g.answers.push({id:crypto.randomUUID(),playerId:p.id,text,votes:[],...(g.mode==='bluff'?{truth:false}:{})} as any);if(g.answers.filter(a=>a.playerId).length===r.players.length)beginVoting(r);else emit(r)});
 s.on('game:vote',(answerId:string)=>{const r=rooms.get(s.data.code);const g=r?.game;const p=r?.players.find(p=>p.id===s.id);if(!r||!g||!p||(g.mode!=='answer'&&g.mode!=='bluff')||g.phase!=='voting')return;const a=g.answers.find(a=>a.id===answerId);if(!a||a.playerId===p.id||g.answers.some(x=>x.votes.includes(p.id)))return;a.votes.push(p.id);if(totalVotes(g)>=r.players.length)finishVoting(r);else emit(r)});
 s.on('who:guess',(x:{answerId:string;playerId:string})=>{const r=rooms.get(s.data.code);const g=r?.game;const me=r?.players.find(p=>p.id===s.id);if(!r||!g||g.mode!=='who'||g.phase!=='guessing'||!me)return;const a=g.answers.find(a=>a.id===x?.answerId);if(!a||a.playerId===me.id||x?.playerId===me.id||!r.players.some(p=>p.id===x?.playerId)||a.guesses.some(q=>q.guesserId===me.id))return;a.guesses.push({guesserId:me.id,guessedPlayerId:x.playerId});if(a.playerId===x.playerId)me.score+=500;const needed=r.players.length*(r.players.length-1);if(g.answers.reduce((n,a)=>n+a.guesses.length,0)>=needed)g.phase='results';emit(r)});
 s.on('draw:submit',(raw:{value:string})=>{const r=rooms.get(s.data.code);const g=r?.game;const p=r?.players.find(p=>p.id===s.id);if(!r||!g||g.mode!=='draw'||g.phase!=='playing'||!p||g.submitted.includes(p.id))return;const task=drawTask(r,g,p.id);if(!task)return;let value=String(raw?.value??'');if(task.kind==='description')value=clean(value,160);else if(!value.startsWith('data:image/png;base64,')||value.length>900000)return s.emit('error:msg','Рисунок слишком большой');if(!value)return;const chain=g.chains.find(c=>c.id===task.chainId);if(!chain)return;chain.entries.push({kind:task.kind as 'drawing'|'description',playerId:p.id,value});g.submitted.push(p.id);advanceDraw(r,g)});

 s.on('monster:submit',(raw:{value:string})=>{const r=rooms.get(s.data.code);const g=r?.game;const p=r?.players.find(p=>p.id===s.id);if(!r||!g||g.mode!=='monster'||g.phase!=='playing'||!p||g.submitted.includes(p.id))return;const value=String(raw?.value??'');if(!value.startsWith('data:image/png;base64,')||value.length>900000)return s.emit('error:msg','Рисунок слишком большой');const chain=monsterTask(r,g,p.id);if(!chain)return;chain.parts.push({kind:(['head','body','legs'] as const)[g.step],playerId:p.id,value});g.submitted.push(p.id);advanceMonster(r,g)});
 s.on('story:submit',(raw:string)=>{const r=rooms.get(s.data.code);const g=r?.game;const p=r?.players.find(p=>p.id===s.id);if(!r||!g||g.mode!=='story'||g.phase!=='playing'||!p||g.submitted.includes(p.id))return;const words=clean(raw,50).split(/\s+/).filter(Boolean);if(words.length!==2)return s.emit('error:msg','Нужно написать ровно 2 слова.');const chain=storyTask(r,g,p.id);if(!chain)return;chain.entries.push({playerId:p.id,words:words.join(' ')});g.submitted.push(p.id);advanceStory(r,g)});
 s.on('tanks:move',(d:{x:number;y:number})=>{const r=rooms.get(s.data.code),g=r?.game;if(!r||!g||g.mode!=='tanks'||g.phase!=='playing')return;const p=g.tanks[s.id];if(!p||p.hp<=0)return;let dx=Math.max(-1,Math.min(1,Number(d?.x)||0)),dy=Math.max(-1,Math.min(1,Number(d?.y)||0));const l=Math.hypot(dx,dy)||1;dx/=l;dy/=l;const speed=Date.now()<p.smallUntil?7.4:5.1,nx=Math.max(24,Math.min(976,p.x+dx*speed)),ny=Math.max(24,Math.min(596,p.y+dy*speed)),rad=Date.now()<p.smallUntil?11:19;if(!tankBlocked(nx,ny,rad)){p.x=nx;p.y=ny;if(dx||dy)p.angle=Math.atan2(dy,dx)}});
 s.on('tanks:shoot',(a:{x:number;y:number})=>{const r=rooms.get(s.data.code),g=r?.game;if(!r||!g||g.mode!=='tanks'||g.phase!=='playing')return;const p=g.tanks[s.id],now=Date.now();if(!p||p.hp<=0||now-p.lastShot<420)return;const ang=Math.atan2(Number(a?.y)-p.y,Number(a?.x)-p.x);p.angle=ang;p.lastShot=now;if(now<p.radialUntil){for(let i=0;i<8;i++)tankBullet(g,s.id,p.x,p.y,i*Math.PI/4,6,30);p.radialUntil=0}else tankBullet(g,s.id,p.x,p.y,ang,now<p.bigUntil?13:6,now<p.bigUntil?55:30)});
 s.on('whale:move',(dir:number)=>{const r=rooms.get(s.data.code),g=r?.game;if(!r||!g||g.mode!=='whale'||g.phase!=='playing')return;const p=g.players[s.id];if(!p||!p.alive)return;const nx=Math.max(.035,Math.min(.965,p.x+Math.sign(Number(dir)||0)*.022));const active=g.obstacles.filter(o=>o.y<.91&&o.y+o.h>.77);const overlap=(x:number,o:WhaleObstacle)=>x+.026>o.x&&x-.026<o.x+o.w;const blocked=active.some(o=>!overlap(p.x,o)&&overlap(nx,o));if(!blocked)p.x=nx});
 s.on('alibi:guess',(x:{evidenceId:string;real:boolean})=>{const r=rooms.get(s.data.code);const g=r?.game;const p=r?.players.find(p=>p.id===s.id);if(!r||!g||g.mode!=='alibi'||g.phase!=='guessing'||!p||p.id!==g.accusedId)return;const e=g.evidence.find(e=>e.id===x?.evidenceId);if(!e||e.guess!==undefined)return;e.guess=!!x.real;if(g.evidence.every(e=>e.guess!==undefined))finishAlibi(r,g.round);else emit(r)});
 s.on('game:pause',()=>{const r=rooms.get(s.data.code);const p=r?.players.find(p=>p.id===s.id);const g=r?.game as any;if(!r||!p?.host||!g||g.phase==='results'||!g.endsAt)return;if(!r.paused){r.paused=true;r.pausedAt=Date.now();sys(r,'Хост поставил таймер на паузу.')}else{const delta=Date.now()-(r.pausedAt||Date.now());g.endsAt+=delta;r.paused=false;r.pausedAt=undefined;sys(r,'Хост продолжил игру.')}emit(r)});
 s.on('game:skip',()=>{const r=rooms.get(s.data.code);const p=r?.players.find(p=>p.id===s.id);const g=r?.game;if(!r||!p||!g||g.phase==='results'||!('endsAt' in g))return;r.skipVotes??=[];if(r.skipVotes.includes(p.id))r.skipVotes=r.skipVotes.filter(id=>id!==p.id);else r.skipVotes.push(p.id);if(r.players.every(x=>r.skipVotes!.includes(x.id))){sys(r,'Все игроки проголосовали за пропуск.');r.skipVotes=[];r.paused=false;r.pausedAt=undefined;if(g.mode==='trap')finishTrap(r);else if(g.mode==='alibi'&&g.phase==='playing')beginAlibiGuessing(r,g.round);else if(g.mode==='alibi'&&g.phase==='guessing')finishAlibi(r,g.round);else emit(r)}else emit(r)});
 s.on('game:next',()=>{const r=rooms.get(s.data.code);const p=r?.players.find(p=>p.id===s.id);if(!r||!p?.host||!r.game||r.game.phase!=='results')return;const {round,maxRounds,mode}=r.game;if(round>=maxRounds)return finishGame(r);if(mode==='answer')startAnswer(r,round+1);else if(mode==='bluff')startBluff(r,round+1);else if(mode==='trap')startTrap(r,round+1);else if(mode==='who')startWho(r,round+1);else if(mode==='draw')startDraw(r,round+1);else if(mode==='alibi')startAlibi(r,round+1);else finishGame(r)});
 s.on('game:lobby',()=>{const r=rooms.get(s.data.code);const p=r?.players.find(p=>p.id===s.id);if(!r||!p?.host)return;r.game=undefined;r.gta=undefined;r.minecraft=undefined;r.finalStandings=undefined;resetReady(r);sys(r,'Хост вернул всех в комнату.');emit(r)});
 s.on('room:leave',()=>{const r=rooms.get(s.data.code);if(!r)return;const i=r.players.findIndex(p=>p.id===s.id);if(i<0)return;const [p]=r.players.splice(i,1);s.leave(r.code);s.data.code=undefined;delete r.minecraft?.players[p.id];delete r.gta?.players[p.id];sys(r,`${p.name} вышел из комнаты.`);if(!r.players.length)rooms.delete(r.code);else{if(p.host)r.players[0].host=true;emit(r)}s.emit('room:left')});
 s.on('host:transfer',(id:string)=>{const r=rooms.get(s.data.code),p=r?.players.find(p=>p.id===s.id),to=r?.players.find(p=>p.id===id);if(!r||!p?.host||!to)return;p.host=false;to.host=true;notify(r,`Хост передан игроку ${to.name}`,'success');emit(r)});
 s.on('admin:open',()=>{const r=rooms.get(s.data.code);const p=r?.players.find(p=>p.id===s.id);if(!r||!p)return;if(p.name.toLocaleLowerCase('ru')==='blagin'||p.name==='Благин'||p.host){r.adminIds??=[];if(!r.adminIds.includes(p.id))r.adminIds.push(p.id);s.emit('admin:panel',{players:r.players})}});
 s.on('admin:kick',(id:string)=>{const r=rooms.get(s.data.code),p=r?.players.find(p=>p.id===s.id);if(!r||!p?.host)return;const target=io.sockets.sockets.get(id);target?.disconnect(true);notify(r,'Игрок удалён','warning')});
 s.on('admin:prefix',(x:{id:string;text:string;color?:string;priority:number})=>{const r=rooms.get(s.data.code),p=r?.players.find(p=>p.id===s.id),t=r?.players.find(p=>p.id===x.id);if(!r||!p?.host||!t)return;t.prefix={text:clean(x.text,30),color:x.color,priority:Number(x.priority)||0};emit(r)});
 s.on('player:avatar',(avatar:string)=>{const r=rooms.get(s.data.code);const p=r?.players.find(p=>p.id===s.id);if(!r||!p||p.name==='петух'||!avatars.includes(avatar))return;p.avatar=avatar;emit(r)});
 s.on('gta:move',(d:{x:number;y:number})=>{const r=rooms.get(s.data.code),g=r?.gta,p=g?.players[s.id];if(!r||!g||!p||p.hp<=0)return;let dx=Math.max(-1,Math.min(1,Number(d?.x)||0)),dy=Math.max(-1,Math.min(1,Number(d?.y)||0));const l=Math.hypot(dx,dy)||1;dx/=l;dy/=l;const drone=[...g.shots].reverse().find(sh=>sh.ownerId===s.id&&sh.kind==='drone');if(drone){if(dx||dy){drone.vx=dx*9;drone.vy=dy*9}return}let speed=7;if(p.vehicleId){const v=g.vehicles.find(v=>v.id===p.vehicleId);if(!v)return;p.x=v.x;p.y=v.y;speed=v.kind==='bike'?13:v.kind==='car'?11:6.5;const nx=Math.max(28,Math.min(1772,v.x+dx*speed)),ny=Math.max(28,Math.min(1172,v.y+dy*speed));if(!gtaBlocked(nx,ny,v.kind==='tank'?28:20)){v.x=nx;v.y=ny;v.angle=Math.atan2(dy,dx);p.x=nx;p.y=ny;p.angle=v.angle}}else{const nx=Math.max(20,Math.min(1780,p.x+dx*speed)),ny=Math.max(20,Math.min(1180,p.y+dy*speed));if(!gtaBlocked(nx,ny,16)){p.x=nx;p.y=ny;p.angle=Math.atan2(dy,dx)}}});
 s.on('gta:shoot',(a:{x:number;y:number})=>{const r=rooms.get(s.data.code),g=r?.gta,p=g?.players[s.id],now=Date.now();if(!r||!g||!p||p.hp<=0)return;const v=p.vehicleId?g.vehicles.find(v=>v.id===p.vehicleId):undefined;const kind:GtaWeapon|'cannon'=v?.kind==='tank'?'cannon':p.weapon;const activeDrone=[...g.shots].reverse().find(sh=>sh.ownerId===s.id&&sh.kind==='drone');if(kind==='drone'&&activeDrone){activeDrone.explodeAt=now;return}const cd=kind==='rifle'?150:kind==='pistol'?430:kind==='grenade'?850:kind==='cannon'?800:1000;if(now-p.lastShot<cd)return;p.lastShot=now;const ang=Math.atan2(Number(a?.y)-p.y,Number(a?.x)-p.x);p.angle=ang;const sp=kind==='grenade'?5:kind==='drone'?6:kind==='rocket'||kind==='cannon'?8:12;g.shots.push({id:crypto.randomUUID(),ownerId:s.id,kind,x:p.x,y:p.y,vx:Math.cos(ang)*sp,vy:Math.sin(ang)*sp,born:now,...(kind==='grenade'?{explodeAt:now+1100}:kind==='drone'?{explodeAt:now+6000}:{})})});
 s.on('gta:action',()=>{const r=rooms.get(s.data.code),g=r?.gta,p=g?.players[s.id];if(!r||!g||!p)return;if(p.vehicleId){const v=g.vehicles.find(v=>v.id===p.vehicleId);if(v)v.driverId=undefined;p.vehicleId=undefined;return}const v=g.vehicles.filter(v=>!v.driverId&&v.hp>0).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];if(v&&Math.hypot(v.x-p.x,v.y-p.y)<70){v.driverId=s.id;p.vehicleId=v.id;p.x=v.x;p.y=v.y}});
 s.on('gta:cycle',()=>{const r=rooms.get(s.data.code),p=r?.gta?.players[s.id];if(!r||!p||!p.owned.length)return;const i=p.owned.indexOf(p.weapon);p.weapon=p.owned[(i+1)%p.owned.length]});
 s.on('gta:exit',()=>{const r=rooms.get(s.data.code),p=r?.players.find(p=>p.id===s.id);if(!r||!p?.host)return;r.gta=undefined;sys(r,'GTA закрыта. Возвращаемся в лобби.');emit(r)});
 s.on('mc:move',(d:{x:number;y:number})=>{const r=rooms.get(s.data.code),mc=r?.minecraft,p=mc?.players[s.id];if(!r||!mc||!p||p.hp<=0)return;const dx=Math.max(-1,Math.min(1,Number(d?.x)||0)),dy=Math.max(-1,Math.min(1,Number(d?.y)||0));const nx=Math.round((p.x+dx)*10)/10,ny=Math.round((p.y+dy)*10)/10;if(mcWalkable(mcTile(mc,Math.round(nx),Math.round(ny)))){p.x=nx;p.y=ny;p.hunger=Math.max(0,p.hunger-.015)}emit(r)});
 s.on('mc:mine',(pos:{x:number;y:number})=>{const r=rooms.get(s.data.code),mc=r?.minecraft,p=mc?.players[s.id];if(!r||!mc||!p)return;const x=Math.round(pos?.x),y=Math.round(pos?.y);if(Math.hypot(p.x-x,p.y-y)>2.2)return;const k=`${x},${y}`,b=mcTile(mc,x,y);if(b==='stone'){p.inv.stone=(p.inv.stone||0)+1;mc.blocks[k]='grass'}else if(b==='wood'){p.inv.wood=(p.inv.wood||0)+2;mc.blocks[k]='grass'}else if(b==='carrot'){p.inv.carrot=(p.inv.carrot||0)+3;mc.blocks[k]='farmland';mc.grown[k]=Date.now()}else if(b==='wall'){p.inv.wall=(p.inv.wall||0)+1;mc.blocks[k]='grass'}else if(b==='door_closed'||b==='door_open'){p.inv.door=(p.inv.door||0)+1;mc.blocks[k]='grass'}emit(r)});
 s.on('mc:craft',(item:string)=>{const r=rooms.get(s.data.code),p=r?.minecraft?.players[s.id];if(!r||!p)return;if(item==='wood_pick'&&(p.inv.wood||0)>=3){p.inv.wood-=3;p.tool='wood_pick'}else if(item==='stone_sword'&&(p.inv.wood||0)>=1&&(p.inv.stone||0)>=2){p.inv.wood--;p.inv.stone-=2;p.tool='stone_sword'}else if(item==='hoe'&&(p.inv.wood||0)>=2&&(p.inv.stone||0)>=1){p.inv.wood-=2;p.inv.stone--;p.tool='hoe'}else if(item==='wall'&&(p.inv.wood||0)>=2){p.inv.wood-=2;p.inv.wall=(p.inv.wall||0)+2}else if(item==='door'&&(p.inv.wood||0)>=3){p.inv.wood-=3;p.inv.door=(p.inv.door||0)+1}emit(r)});
 s.on('mc:place',(x:{x:number;y:number;item:string})=>{const r=rooms.get(s.data.code),mc=r?.minecraft,p=mc?.players[s.id];if(!r||!mc||!p)return;const px=Math.round(x?.x),py=Math.round(x?.y),k=`${px},${py}`;if(Math.hypot(p.x-px,p.y-py)>2.2)return;const b=mcTile(mc,px,py);if(x.item==='wall'&&(p.inv.wall||0)>0&&['grass','sand','farmland'].includes(b)){p.inv.wall--;mc.blocks[k]='wall'}else if(x.item==='door'&&(p.inv.door||0)>0&&['grass','sand','farmland'].includes(b)){p.inv.door--;mc.blocks[k]='door_closed'}emit(r)});
 s.on('mc:use',(pos:{x:number;y:number})=>{const r=rooms.get(s.data.code),mc=r?.minecraft,p=mc?.players[s.id];if(!r||!mc||!p)return;const x=Math.round(pos?.x),y=Math.round(pos?.y),k=`${x},${y}`;if(Math.hypot(p.x-x,p.y-y)>2.2)return;const b=mcTile(mc,x,y);if(b==='door_closed')mc.blocks[k]='door_open';else if(b==='door_open')mc.blocks[k]='door_closed';else if(p.tool==='hoe'&&b==='grass'){let water=false;for(let yy=y-3;yy<=y+3;yy++)for(let xx=x-3;xx<=x+3;xx++)if(mcTile(mc,xx,yy)==='water')water=true;if(water){mc.blocks[k]='farmland';mc.grown[k]=Date.now()}}emit(r)});
 s.on('mc:eat',()=>{const r=rooms.get(s.data.code),p=r?.minecraft?.players[s.id];if(!r||!p||(p.inv.carrot||0)<1)return;p.inv.carrot--;p.hunger=Math.min(20,p.hunger+5);emit(r)});
 s.on('mc:feed',(mobId:string)=>{const r=rooms.get(s.data.code),mc=r?.minecraft,p=mc?.players[s.id],m=mc?.mobs.find(m=>m.id===mobId);if(!r||!mc||!p||!m||m.kind!=='pig'||(p.inv.carrot||0)<1||Math.hypot(p.x-m.x,p.y-m.y)>2)return;p.inv.carrot--;m.breed=Date.now();const mate=mc.mobs.find(q=>q.id!==m.id&&q.kind==='pig'&&q.breed&&Date.now()-q.breed<12000&&Math.hypot(q.x-m.x,q.y-m.y)<3);if(mate){const q=mcSpawn(mc,Math.round((m.x+mate.x)/2),Math.round((m.y+mate.y)/2));mc.mobs.push({id:crypto.randomUUID(),kind:'pig',x:q.x,y:q.y,hp:6});m.breed=0;mate.breed=0}emit(r)});
 s.on('mc:attack',(targetId:string)=>{const r=rooms.get(s.data.code),mc=r?.minecraft,a=mc?.players[s.id],b=mc?.players[targetId];if(!r||!mc||!a)return;if(b&&Math.hypot(a.x-b.x,a.y-b.y)<=2)b.hp=Math.max(0,b.hp-(a.tool==='stone_sword'?6:2));else{const m=mc.mobs.find(m=>m.id===targetId);if(m&&Math.hypot(a.x-m.x,a.y-m.y)<=2){m.hp-=a.tool==='stone_sword'?6:2;if(m.hp<=0){if(m.kind==='pig'||m.kind==='cow'){a.inv.food=(a.inv.food||0)+2;a.hunger=Math.min(20,a.hunger+1)}mc.mobs=mc.mobs.filter(q=>q.id!==m.id)}}}emit(r)});
 s.on('mc:exit',()=>{const r=rooms.get(s.data.code);const p=r?.players.find(p=>p.id===s.id);if(!r||!p?.host)return;r.minecraft=undefined;sys(r,'Minecraft закрыт. Возвращаемся в лобби.');emit(r)});
 s.on('draw:line',(data:any)=>{const r=rooms.get(s.data.code);if(!r||r.game?.mode!=='draw')return;io.to(r.code).emit('draw:line',data)});
 s.on('draw:clear',()=>{const r=rooms.get(s.data.code);if(r)io.to(r.code).emit('draw:clear')});
 s.on('chat:send',(raw:string)=>{const r=rooms.get(s.data.code);const p=r?.players.find(p=>p.id===s.id);const text=clean(raw,300);if(!r||!p||!text)return;if(text.toLocaleLowerCase('ru')==='/minecraft'){makeMinecraft(r);return}if(text.toLocaleLowerCase('ru')==='/gta'){makeGta(r);return}r.messages.push({id:crypto.randomUUID(),playerId:p.id,name:p.name,text,at:Date.now()});r.messages=r.messages.slice(-100);const g=r.game;if(g?.mode==='trap'&&g.phase==='playing'){for(const m of g.missions.filter(m=>!m.done&&m.targetId===p.id)){const words=text.toLocaleLowerCase('ru').split(/[^\p{L}\p{N}]+/u).filter(Boolean);if(words.includes(m.trigger.toLocaleLowerCase('ru'))){m.done=true;const hunter=r.players.find(x=>x.id===m.playerId);if(hunter){hunter.score+=500;g.completed?.push({hunterId:m.playerId,targetId:p.id,trigger:m.trigger,message:text});sys(r,`${hunter.name} выполнил свою подставу.`)}}}if(g.missions.every(m=>m.done))setTimeout(()=>finishTrap(r),500)}emit(r)});
 s.on('disconnect',()=>{const r=rooms.get(s.data.code);if(!r)return;const i=r.players.findIndex(p=>p.id===s.id);if(i<0)return;const [p]=r.players.splice(i,1);delete r.minecraft?.players[p.id];delete r.gta?.players[p.id];sys(r,`${p.name} вышел из комнаты.`);if(!r.players.length){rooms.delete(r.code);return}if(p.host)r.players[0].host=true;if(r.game&&r.players.length<2){finishGame(r);return}if(r.game?.mode==='draw'||r.game?.mode==='monster'||r.game?.mode==='story'){finishGame(r);return}if(r.game&&r.game.mode!=='trap'&&r.game.phase==='answering'&&r.game.answers.filter(a=>a.playerId).length===r.players.length)beginVoting(r);else emit(r)});
});
// Production: serve the Vite client from the same Render web service.
const clientDist=path.join(process.cwd(),'dist');
app.use(express.static(clientDist));
app.get(/^(?!\/socket\.io|\/health).*/,(_req,res)=>{
  res.sendFile(path.join(clientDist,'index.html'));
});

const port=Number(process.env.PORT)||3001;
http.listen(port,()=>console.log(`Еблангейм server :${port}`));
